#!/bin/bash
b=""
if [ -f "/usr/include/clpoly.hh"  ] 
then
    read -p  "Existing file, do you want to overwrite? (y/n,default=y):" v
    if [ -z $v ]
    then
        v="y"
    fi
    b="z"
    if [ $v != "y" ]
    then
        echo  -e "\033[31m Installation Stoped. \033[0m"
        exit 0
    fi
fi
list=`ls clpoly|grep hh`
if [ -z $b ]
then
    for i in $list
    do
        if [ -f "/usr/include/clpoly/$i"  ] 
        then
            read -p  "Existing file, do you want to overwrite? (y/n,default=y):" v
            if [ -z $v ]
            then
                v="y"
            fi
            if [ $v != "y" ]
            then
                echo  -e "\033[31m Installation Stoped. \033[0m"
                exit 0
            fi
            break
        fi
    done
fi

echo "cp ./clpoly.hh /usr/include/clpoly.hh"
cp ./clpoly.hh /usr/include/clpoly.hh
if [ $? -ne 0 ]
then
    echo  -e "\033[31m Installation Failed. \033[0m"
    exit 1
fi
if ! [ -d /usr/include/clpoly ]
then
    mkdir /usr/include/clpoly
    if [ $? -ne 0 ]
    then
        echo  -e "\033[31m Installation Failed. \033[0m"
        exit 1
    fi
fi


for i in $list
do
    echo "cp clpoly/$i  /usr/include/clpoly/$i"
    cp clpoly/$i  /usr/include/clpoly/$i
    if [ $? -ne 0 ]
    then
        echo  -e "\033[31m Installation Failed. \033[0m"
        exit 1
    fi
done
echo  -e "\033[32m Installation Successful. \033[0m"