#!/bin/bash

if [ -f "/usr/include/clpoly.hh"  ] 
then
    echo "rm  /usr/include/clpoly.hh"
    rm  /usr/include/clpoly.hh
    if [ $? -ne 0 ]
    then
        echo  -e "\033[31m Uninstallation Failed. \033[0m"
        exit 1
    fi
fi
if [ -d "/usr/include/clpoly" ]
then
    list=`ls clpoly|grep hh`
    for i in $list
    do
        if [ -f "/usr/include/clpoly/$i"  ] 
        then
            echo "rm  /usr/include/clpoly/$i"
            rm  /usr/include/clpoly/$i
            if [ $? -ne 0 ]
            then
                echo  -e "\033[31m Uninstallation Failed. \033[0m"
                exit 1
            fi
        fi
    done
    c=`ls -a /usr/include/clpoly|wc -l`
    if [ $c -eq 2 ]
    then 
        echo "rmdir  /usr/include/clpoly"
        rmdir  /usr/include/clpoly
    fi
fi
echo -e "\033[32m Uninstallation Successful. \033[0m"
