#!/usr/bin/env python3
"""
生成完整的 Lean 文件：prelude + 外部声明 + 全部翻译函数。
"""

import sys
sys.path.insert(0, ".")

from clang_hybrid import parse_file
from ssa_transform import transform_func
from ub_collector import collect_all, inject_obligations
from lean_codegen import gen_ssa_func, PRELUDE
import re


import os

MODEL_PATH = os.path.join(os.path.dirname(__file__), "clpoly_model.lean")

def _read_model() -> str:
    """读取 clpoly_model.lean，去掉末尾的 #eval 测试。"""
    with open(MODEL_PATH) as f:
        lines = f.readlines()
    # 去掉 §6 验证测试部分
    result = []
    for line in lines:
        if line.strip().startswith("-- §6.") or line.strip().startswith("#eval"):
            break
        result.append(line)
    return "".join(result)


LEAN_PRELUDE = """-- Auto-generated by cpp2lean
-- CLPoly polynomial_factorize_zp.hh → Lean IR

set_option autoImplicit false

-- ============================================================
-- 类型定义
-- ============================================================

structure Zp where
  val : UInt64
  prime : UInt64
deriving Repr, Inhabited

-- Zp 从 Int 构造（CLPoly 的 Zp(int64_t, uint64_t)）
def Zp.ofInt (v : Int) (p : UInt64) : Zp :=
  ⟨(v % p.toNat).toNat.toUInt64, p⟩

structure UMonomial where
  deg : UInt64
deriving Repr, Inhabited

abbrev SparsePolyZp := Array (UMonomial × Zp)

-- Array 辅助
def Array.front! {α : Type} [Inhabited α] (a : Array α) : α := a[0]!

-- UInt64 / Nat 互操作（C++ 用 uint64_t 索引，Lean Array 用 Nat）
instance : LT UInt64 where lt a b := a.toNat < b.toNat
instance : LE UInt64 where le a b := a.toNat ≤ b.toNat
instance : DecidableEq UInt64 := inferInstance
instance {α : Type} : GetElem (Array α) UInt64 α (fun a i => i.toNat < a.size) where
  getElem a i h := a[i.toNat]

@[inline] def Array.size_u64 (a : Array α) : UInt64 := a.size.toUInt64

-- ============================================================
-- 外部函数声明（CLPoly 其他模块提供，此处为 opaque）
-- ============================================================

opaque derivative_ir (f : SparsePolyZp) : SparsePolyZp
opaque polynomial_GCD_ir (f g : SparsePolyZp) : SparsePolyZp
opaque pair_vec_div_ir (a b c d : SparsePolyZp) : Unit
opaque get_deg_ir (f : SparsePolyZp) : UInt64
opaque normalize_ir (f : SparsePolyZp) : SparsePolyZp
opaque comp_ir (f : SparsePolyZp) : UInt64
opaque inv_ir (a : Zp) : Zp
opaque number_ir (a : UInt64) (p : UInt64) : Zp

-- ============================================================
-- 翻译函数
-- ============================================================
"""


def main():
    filename = sys.argv[1] if len(sys.argv) > 1 else "../../clpoly/polynomial_factorize_zp.hh"
    args = ["-std=c++17", "-I../../"]

    funcs = parse_file(filename, args=args, target_file="factorize_zp")

    # 翻译 + UB 注入
    ssa_funcs = []
    for f in funcs:
        sf = transform_func(f)
        obs = collect_all(sf)
        inject_obligations(sf, obs)
        ssa_funcs.append(sf)

    # 按调用图排序：被调函数在前
    ordered = _topological_sort(ssa_funcs)

    # 输出：model + 翻译函数
    model_code = _read_model()
    print(model_code)
    print("-- ============================================================")
    print("-- 翻译函数（由 cpp2lean 自动生成）")
    print("-- ============================================================")
    print()
    for sf in ordered:
        print(gen_ssa_func(sf))
        print()


def _topological_sort(funcs):
    """按调用图拓扑排序：被调函数在调用者之前。"""
    name_to_func = {sf.name: sf for sf in funcs}
    translated = set(name_to_func.keys())

    # 构建依赖图
    deps = {}
    for sf in funcs:
        code = gen_ssa_func(sf)
        called = set()
        for m in re.findall(r'(\w+)_ir\b', code):
            if m in translated and m != sf.name:
                called.add(m)
        deps[sf.name] = called

    # Kahn's algorithm
    in_degree = {name: 0 for name in translated}
    for name, callees in deps.items():
        for callee in callees:
            if callee in in_degree:
                in_degree[callee] = in_degree.get(callee, 0)  # no increment for callee

    # 反转：如果 A 调用 B，B 的入度++（B 要先输出）
    reverse_deps = {name: set() for name in translated}
    for name, callees in deps.items():
        for callee in callees:
            if callee in reverse_deps:
                reverse_deps[callee].add(name)

    in_deg = {name: len(callees & translated) for name, callees in deps.items()}
    queue = [name for name, d in in_deg.items() if d == 0]
    result = []
    visited = set()

    while queue:
        name = queue.pop(0)
        if name in visited:
            continue
        visited.add(name)
        result.append(name_to_func[name])
        for dependent in reverse_deps.get(name, []):
            in_deg[dependent] -= 1
            if in_deg[dependent] <= 0 and dependent not in visited:
                queue.append(dependent)

    # 处理循环依赖（如递归函数）
    for sf in funcs:
        if sf.name not in visited:
            result.append(sf)

    return result


if __name__ == "__main__":
    main()
