import CLPoly.Refinement.Generated
import CLPoly.Refinement.FactorZZ
import CLPoly.Refinement.Recombine

#print axioms Refinement.__squarefree_Zp_raw_ir_refines_sqfZp
#print axioms Refinement.__ddf_Zp_raw_ir_refines_ddf
#print axioms Refinement.__edf_Zp_raw_ir_refines_edf
#print axioms Refinement.__hensel_lift_upoly_raw_ir_refines
#print axioms Refinement.StrictRecombine.zassenhausAttempt_extracted_factor_mod_eq_selected
#print axioms Refinement.StrictRecombine.scanZassenhausCombinations_extracted_mod_certificate
#print axioms Refinement.StrictRecombine.removeCombination_preserves_pointwise
#print axioms Refinement.StrictRecombine.symmetricModRaw_toPoly_coefficients_bounded
#print axioms Refinement.StrictRecombine.symmetric_recovery_closed_left
#print axioms Refinement.StrictRecombine.upolyNormL2SqRaw_eq_stored_sum
#print axioms Refinement.StrictRecombine.binomialLoopRaw_eq_choose
#print axioms Refinement.StrictRecombine.binomialRaw_degree_half_eq_choose
#print axioms Refinement.StrictRecombine.isqrtCeilLoopRaw_eq_sqrtIter
#print axioms Refinement.StrictRecombine.isqrtCeilRaw_nonnegative_and_square_ge
#print axioms Refinement.StrictRecombine.mignotteBoundRaw_eq_choose_isqrt
#print axioms Refinement.StrictRecombine.upolyNormL2SqRaw_eq_coeff_range_sum
#print axioms Refinement.StrictRecombine.divisor_coeff_le_generated_mignotte_norm
#print axioms Refinement.StrictRecombine.mignotteBoundRaw_bounds_divisor
#print axioms Refinement.StrictRecombine.hensel_output_modulus_bounds_scaled_divisor
#print axioms Refinement.StrictRecombine.symmetricModRaw_recovers_strictly_bounded_target
#print axioms Refinement.StrictFactorZZ.selectionHenselFactors_pointwise_associated
#print axioms Refinement.StrictFactorZZ.selectionHenselFactors_product_associated
#print axioms Refinement.StrictFactorZZ.integer_divisor_mod_associated_hensel_sublist
#print axioms Refinement.StrictFactorZZ.integer_divisor_mod_has_legal_hensel_candidate
#print axioms Refinement.StrictHensel.HenselLiftRecursiveCorrect.preserves_not_mem
#print axioms Refinement.StrictHensel.henselTreeBuildTopology_indices_nodup_bounded
#print axioms Refinement.StrictHensel.henselExtractedFactors_eq_of_lookups
#print axioms Refinement.StrictHensel.HenselLiftRecursiveCorrect.extractedFactors_product
