-- Auto-generated by cpp2lean v2 Pass 9 (refine_gen)
-- L1 → L2 refinement theorem skeletons

import CLPoly.Algorithm.DDF
import CLPoly.Model
import CLPoly.Generated.Corpus
import CLPoly.Generated.StrictDDF
import CLPoly.Refinement.Basic
import CLPoly.Refinement.SquarefreeZp
import CLPoly.Math.Univariate

set_option autoImplicit false

open Polynomial
open CLPoly.Math

namespace Refinement


variable {p : ℕ} [hp : Fact (Nat.Prime p)]

/-- The strict total entry is emitted from the same MIR equation as the legacy
partial entry.  Non-recursive entries therefore agree by the raw equation
theorem, with no algorithm replacement involved. -/
theorem strict_make_zp_eq_raw (val : Int64) (q : UInt64) :
    Generated.StrictDDF.__make_zp_ir val q =
      Generated.__make_zp_ir val q := by
  rw [Generated.__make_zp_ir.eq_1]
  rfl

theorem strict_upoly_mod_eq_raw (f g : SparsePolyZp) :
    Generated.StrictDDF.__upoly_mod_ir f g =
      Generated.__upoly_mod_ir f g := by
  rw [Generated.__upoly_mod_ir.eq_1]
  rfl

/-- `__upoly_mod_ir` 在规范输入上同时保持稀疏规范形，并精化为
mathlib 的首一多项式余式。 -/
private theorem upoly_mod_step_data (h2p : 2 * p ≤ UInt64.size)
    (hp2 : p * p ≤ UInt64.size) (f g : SparsePolyZp)
    (hf : CanonicalRep p f) (hg : CanonicalRep p g) (hg_ne : ¬g.isEmpty)
    (hg_monic : Monic (SparsePolyZp.toPoly p g)) :
    CanonicalRep p (Generated.__upoly_mod_ir f g) ∧
      SparsePolyZp.toPoly p (Generated.__upoly_mod_ir f g) =
        SparsePolyZp.toPoly p f %ₘ SparsePolyZp.toPoly p g := by
  have hmod := __upoly_mod_ir_refines p f g (wellFormed_of_canonical f hf) hf.2.2
    (wellFormed_of_canonical g hg) hg.2.2 h2p
  rw [hmod]
  exact ⟨divmod_snd_canonical f g hf hg hg_ne (by nlinarith),
    divmod_snd_toPoly_eq_modByMonic h2p hp2 f g hf hg hg_ne hg_monic⟩

/-- DDF/powmod 中的“先乘后取模”单步语义。 -/
private theorem mul_mod_step_data (h2p : 2 * p ≤ UInt64.size)
    (hp2 : p * p ≤ UInt64.size) (a b m : SparsePolyZp)
    (ha : CanonicalRep p a) (hb : CanonicalRep p b) (hm : CanonicalRep p m)
    (hm_ne : ¬m.isEmpty) (hm_monic : Monic (SparsePolyZp.toPoly p m)) :
    CanonicalRep p (Generated.__upoly_mod_ir (a * b) m) ∧
      SparsePolyZp.toPoly p (Generated.__upoly_mod_ir (a * b) m) =
        (SparsePolyZp.toPoly p a * SparsePolyZp.toPoly p b) %ₘ
          SparsePolyZp.toPoly p m := by
  have hab := canonicalRep_mul hp2 a b ha hb
  have hstep := upoly_mod_step_data h2p hp2 (a * b) m hab hm hm_ne hm_monic
  refine ⟨hstep.1, ?_⟩
  rw [hstep.2, SparsePolyZp.toPoly_mul p h2p hp2 a b ha.2.2 hb.2.2]

private lemma modByMonic_idem (a m : Polynomial (ZMod p)) (hm : Monic m) :
    (a %ₘ m) %ₘ m = a %ₘ m :=
  (modByMonic_eq_self_iff hm).mpr (degree_modByMonic_lt a hm)

private lemma mul_modByMonic_congr {a a' b b' m : Polynomial (ZMod p)}
    (ha : a %ₘ m = a' %ₘ m) (hb : b %ₘ m = b' %ₘ m) :
    (a * b) %ₘ m = (a' * b') %ₘ m := by
  calc
    (a * b) %ₘ m = (a %ₘ m) * (b %ₘ m) %ₘ m := Polynomial.mul_modByMonic _ _ _
    _ = (a' %ₘ m) * (b' %ₘ m) %ₘ m := by rw [ha, hb]
    _ = (a' * b') %ₘ m := (Polynomial.mul_modByMonic _ _ _).symm

private lemma pow_modByMonic_congr {a b m : Polynomial (ZMod p)}
    (h : a %ₘ m = b %ₘ m) : ∀ n : Nat, (a ^ n) %ₘ m = (b ^ n) %ₘ m := by
  intro n
  induction n with
  | zero => simp
  | succ n ih =>
      rw [pow_succ, pow_succ]
      exact mul_modByMonic_congr ih h

private lemma singleton_one_data (q : UInt64) (hq : q.toNat = p) :
    CanonicalRep p
        (#[(UMonomial.mk (0 : Int32), Zp.ofInt (1 : Int) q)] : SparsePolyZp) ∧
      SparsePolyZp.toPoly p
          (#[(UMonomial.mk (0 : Int32), Zp.ofInt (1 : Int) q)] : SparsePolyZp) = 1 := by
  subst p
  have hqgt : 1 < q.toNat := Nat.Prime.one_lt hp.out
  have hmod : (1 : Int) % (q.toNat : Int) = 1 := by
    apply Int.emod_eq_of_lt
    · norm_num
    · exact_mod_cast hqgt
  simp [CanonicalRep, SparsePolyZp.Sorted, SparsePolyZp.NonZeroB,
    SparsePolyZp.AllReduced, SparsePolyZp.toPoly, listSum, Zp.Reduced,
    SparsePolyZp.sortedListB, SparsePolyZp.nonzeroListB,
    Zp.ofInt, Zp.toZMod, hmod, hqgt]

private lemma singleton_x_data (q : UInt64) (hq : q.toNat = p) :
    CanonicalRep p
        (#[(UMonomial.mk (1 : Int32), Zp.ofInt (1 : Int) q)] : SparsePolyZp) ∧
      SparsePolyZp.toPoly p
          (#[(UMonomial.mk (1 : Int32), Zp.ofInt (1 : Int) q)] : SparsePolyZp) = X := by
  subst p
  have hqgt : 1 < q.toNat := Nat.Prime.one_lt hp.out
  have hmod : (1 : Int) % (q.toNat : Int) = 1 := by
    apply Int.emod_eq_of_lt
    · norm_num
    · exact_mod_cast hqgt
  simp [CanonicalRep, SparsePolyZp.Sorted, SparsePolyZp.NonZeroB,
    SparsePolyZp.AllReduced, SparsePolyZp.toPoly, listSum, Zp.Reduced,
    SparsePolyZp.sortedListB, SparsePolyZp.nonzeroListB,
    Zp.ofInt, Zp.toZMod, hmod, hqgt]
  rw [show (Int64.toUInt64 1).toNat = 1 by rfl,
    Polynomial.monomial_one_one_eq_X]

private lemma canonicalRep_neg (f : SparsePolyZp) (hf : CanonicalRep p f) :
    CanonicalRep p (-f) := by
  refine ⟨?_, ?_, SparsePolyZp.WellFormed_arr.neg p f hf.2.2⟩
  · change SparsePolyZp.sortedListB (SparsePolyZp.negImpl f).toList = true
    unfold SparsePolyZp.negImpl
    rw [Array.toList_map]
    exact (SparsePolyZp.sortedListB_map_fst _
      (by rintro ⟨m, c⟩; rfl) f.toList).trans hf.1
  · change SparsePolyZp.nonzeroListB (SparsePolyZp.negImpl f).toList = true
    unfold SparsePolyZp.negImpl
    rw [Array.toList_map]
    have aux : ∀ xs : List (UMonomial × Zp),
        SparsePolyZp.AllReduced p xs →
        SparsePolyZp.nonzeroListB xs = true →
        SparsePolyZp.nonzeroListB (xs.map fun x => (x.1, -x.2)) = true := by
      intro xs
      induction xs with
      | nil => simp [SparsePolyZp.nonzeroListB]
      | cons a rest ih =>
          intro hred hnz
          rw [List.map_cons, SparsePolyZp.nonzeroListB_cons]
          have ha_red := hred a List.mem_cons_self
          have hrest_red : SparsePolyZp.AllReduced p rest :=
            fun x hx => hred x (List.mem_cons_of_mem _ hx)
          have hnz' := (SparsePolyZp.nonzeroListB_cons a rest).mp hnz
          have hprime_pos : 0 < a.2.prime.toNat := by
            rw [ha_red.1]
            exact hp.out.pos
          have hval_lt : a.2.val < a.2.prime := by
            rw [UInt64.lt_iff_toNat_lt, ha_red.1]
            exact ha_red.2
          exact ⟨SparsePolyZp.Zp_neg_nonzero a.2 hval_lt hnz'.1 hprime_pos,
            ih hrest_red hnz'.2⟩
    exact aux f.toList hf.2.2 hf.2.1

private lemma canonicalRep_sub (f g : SparsePolyZp)
    (hf : CanonicalRep p f) (hg : CanonicalRep p g) : CanonicalRep p (f - g) := by
  change CanonicalRep p (f + -g)
  rw [canonicalRep_iff_canonical]
  exact SparsePolyZp.Canonical.add p f (-g)
    ((canonicalRep_iff_canonical f).mp hf)
    ((canonicalRep_iff_canonical (-g)).mp (canonicalRep_neg g hg))

private lemma front_prime_of_canonical (f : SparsePolyZp)
    (hf : CanonicalRep p f) (hne : ¬f.isEmpty) :
    (SparsePolyZp.front! f).snd.prime.toNat = p := by
  have hsize : 0 < f.size := by
    rw [Array.isEmpty_iff_size_eq_zero] at hne
    omega
  have hlen : 0 < f.toList.length := by simpa using hsize
  have hget : f[0]! = f.toList.get ⟨0, hlen⟩ := by
    simp [getElem!_def, getElem?_def, hsize, hlen]
  have hmem : f[0]! ∈ f.toList := by
    rw [hget]
    exact List.get_mem _ _
  simpa [SparsePolyZp.front!] using (hf.2.2 f[0]! hmem).1

set_option maxHeartbeats 0 in
/-- 二进制 powmod 内循环在非负整数指数上的精确语义。 -/
private theorem powmod_loop_refines (h2p : 2 * p ≤ UInt64.size)
    (hp2 : p * p ≤ UInt64.size) (m : SparsePolyZp)
    (hm : CanonicalRep p m) (hm_ne : ¬m.isEmpty)
    (hm_monic : Monic (SparsePolyZp.toPoly p m)) :
    ∀ (n : Nat) (b r : SparsePolyZp),
      CanonicalRep p b → CanonicalRep p r →
      SparsePolyZp.toPoly p b %ₘ SparsePolyZp.toPoly p m = SparsePolyZp.toPoly p b →
      SparsePolyZp.toPoly p r %ₘ SparsePolyZp.toPoly p m = SparsePolyZp.toPoly p r →
      let out := Generated.upolyPowmodLoopSafe Generated.__upoly_mod_ir n b r m
      CanonicalRep p out ∧
        SparsePolyZp.toPoly p out =
          (SparsePolyZp.toPoly p r * SparsePolyZp.toPoly p b ^ n) %ₘ
            SparsePolyZp.toPoly p m := by
  intro n
  induction n using Nat.strongRecOn with
  | ind n ih =>
      intro b r hb hr hbmod hrmod
      by_cases hn : n = 0
      · subst n
        rw [Generated.upolyPowmodLoopSafe]
        simpa [hrmod]
      · have hnpos : 0 < n := Nat.pos_of_ne_zero hn
        let k := n / 2
        have hklt : k < n := Nat.div_lt_self hnpos (by norm_num)
        by_cases hodd : n % 2 ≠ 0
        · let r' := Generated.__upoly_mod_ir (r * b) m
          have hodd1 : n % 2 = 1 := by omega
          have hr'data := mul_mod_step_data h2p hp2 r b m hr hb hm hm_ne hm_monic
          have hr'can : CanonicalRep p r' := by simpa [r'] using hr'data.1
          have hr'poly : SparsePolyZp.toPoly p r' =
              (SparsePolyZp.toPoly p r * SparsePolyZp.toPoly p b) %ₘ
                SparsePolyZp.toPoly p m := by simpa [r'] using hr'data.2
          have hr'mod : SparsePolyZp.toPoly p r' %ₘ SparsePolyZp.toPoly p m =
              SparsePolyZp.toPoly p r' := by
            rw [hr'poly]
            exact modByMonic_idem _ _ hm_monic
          by_cases hkpos : 0 < k
          · let b' := Generated.__upoly_mod_ir (b * b) m
            have hb'data := mul_mod_step_data h2p hp2 b b m hb hb hm hm_ne hm_monic
            have hb'can : CanonicalRep p b' := by simpa [b'] using hb'data.1
            have hb'poly : SparsePolyZp.toPoly p b' =
                (SparsePolyZp.toPoly p b * SparsePolyZp.toPoly p b) %ₘ
                  SparsePolyZp.toPoly p m := by simpa [b'] using hb'data.2
            have hb'mod : SparsePolyZp.toPoly p b' %ₘ SparsePolyZp.toPoly p m =
                SparsePolyZp.toPoly p b' := by
              rw [hb'poly]
              exact modByMonic_idem _ _ hm_monic
            have hrec := ih k hklt b' r' hb'can hr'can hb'mod hr'mod
            rw [Generated.upolyPowmodLoopSafe]
            simp only [hnpos, if_pos, hodd, bne_iff_ne, ne_eq, k, hkpos]
            dsimp only at hrec ⊢
            refine ⟨hrec.1, hrec.2.trans ?_⟩
            have hnform : n = 2 * k + 1 := by omega
            calc
              (SparsePolyZp.toPoly p r' * SparsePolyZp.toPoly p b' ^ k) %ₘ
                  SparsePolyZp.toPoly p m =
                  ((SparsePolyZp.toPoly p r * SparsePolyZp.toPoly p b) *
                    (SparsePolyZp.toPoly p b * SparsePolyZp.toPoly p b) ^ k) %ₘ
                    SparsePolyZp.toPoly p m := mul_modByMonic_congr
                      (by rw [hr'poly, modByMonic_idem _ _ hm_monic])
                      (pow_modByMonic_congr
                        (by rw [hb'poly, modByMonic_idem _ _ hm_monic]) k)
              _ = (SparsePolyZp.toPoly p r * SparsePolyZp.toPoly p b ^ n) %ₘ
                    SparsePolyZp.toPoly p m := by rw [hnform]; congr 1 <;> ring
          · have hkzero : k = 0 := by omega
            rw [Generated.upolyPowmodLoopSafe]
            have hn_one : n = 1 := by omega
            subst n
            simpa [Generated.upolyPowmodLoopSafe] using hr'data
        · have heven : n % 2 = 0 := by omega
          have hkpos : 0 < k := by
            dsimp [k]
            omega
          let b' := Generated.__upoly_mod_ir (b * b) m
          have hb'data := mul_mod_step_data h2p hp2 b b m hb hb hm hm_ne hm_monic
          have hb'can : CanonicalRep p b' := by simpa [b'] using hb'data.1
          have hb'poly : SparsePolyZp.toPoly p b' =
              (SparsePolyZp.toPoly p b * SparsePolyZp.toPoly p b) %ₘ
                SparsePolyZp.toPoly p m := by simpa [b'] using hb'data.2
          have hb'mod : SparsePolyZp.toPoly p b' %ₘ SparsePolyZp.toPoly p m =
              SparsePolyZp.toPoly p b' := by
            rw [hb'poly]
            exact modByMonic_idem _ _ hm_monic
          have hrec := ih k hklt b' r hb'can hr hb'mod hrmod
          rw [Generated.upolyPowmodLoopSafe]
          simp only [hnpos, if_pos, heven, k, hkpos]
          dsimp only at hrec ⊢
          refine ⟨hrec.1, hrec.2.trans ?_⟩
          have hnform : n = 2 * k := by omega
          calc
            (SparsePolyZp.toPoly p r * SparsePolyZp.toPoly p b' ^ k) %ₘ
                SparsePolyZp.toPoly p m =
                (SparsePolyZp.toPoly p r *
                  (SparsePolyZp.toPoly p b * SparsePolyZp.toPoly p b) ^ k) %ₘ
                  SparsePolyZp.toPoly p m := mul_modByMonic_congr rfl
                    (pow_modByMonic_congr
                      (by rw [hb'poly, modByMonic_idem _ _ hm_monic]) k)
            _ = (SparsePolyZp.toPoly p r * SparsePolyZp.toPoly p b ^ n) %ₘ
                  SparsePolyZp.toPoly p m := by rw [hnform]; congr 1 <;> ring

/-- The total powmod entry point implements polynomial exponentiation modulo a
nonempty monic modulus. -/
private theorem upoly_powmod_safe_refines (h2p : 2 * p ≤ UInt64.size)
    (hp2 : p * p ≤ UInt64.size) (base m : SparsePolyZp) (n : Nat)
    (hn : 0 < n) (hbase : CanonicalRep p base) (hm : CanonicalRep p m)
    (hm_ne : ¬m.isEmpty) (hm_monic : Monic (SparsePolyZp.toPoly p m))
    (hm_deg : 0 < (SparsePolyZp.toPoly p m).natDegree)
    (hprime : (SparsePolyZp.front! m).snd.prime.toNat = p) :
    CanonicalRep p
        (Generated.upolyPowmodSafe Generated.__upoly_mod_ir base (n : Int) m) ∧
      SparsePolyZp.toPoly p
          (Generated.upolyPowmodSafe Generated.__upoly_mod_ir base (n : Int) m) =
        SparsePolyZp.toPoly p base ^ n %ₘ SparsePolyZp.toPoly p m := by
  have hbdata := upoly_mod_step_data h2p hp2 base m hbase hm hm_ne hm_monic
  have honedata := singleton_one_data (SparsePolyZp.front! m).snd.prime hprime
  have hbmod : SparsePolyZp.toPoly p (Generated.__upoly_mod_ir base m) %ₘ
      SparsePolyZp.toPoly p m =
      SparsePolyZp.toPoly p (Generated.__upoly_mod_ir base m) := by
    rw [hbdata.2]
    exact modByMonic_idem _ _ hm_monic
  have honemod : SparsePolyZp.toPoly p
        (#[(UMonomial.mk (0 : Int32),
          Zp.ofInt (1 : Int) (SparsePolyZp.front! m).snd.prime)] : SparsePolyZp) %ₘ
        SparsePolyZp.toPoly p m =
      SparsePolyZp.toPoly p
        (#[(UMonomial.mk (0 : Int32),
          Zp.ofInt (1 : Int) (SparsePolyZp.front! m).snd.prime)] : SparsePolyZp) := by
    rw [honedata.2]
    apply (modByMonic_eq_self_iff hm_monic).mpr
    have hm0 : SparsePolyZp.toPoly p m ≠ 0 := by
      intro hzero
      simp [hzero] at hm_deg
    simp [degree_eq_natDegree hm0, hm_deg]
  have hloop := powmod_loop_refines h2p hp2 m hm hm_ne hm_monic n
    (Generated.__upoly_mod_ir base m)
    (#[(UMonomial.mk (0 : Int32),
      Zp.ofInt (1 : Int) (SparsePolyZp.front! m).snd.prime)] : SparsePolyZp)
    hbdata.1 honedata.1 hbmod honemod
  rw [Generated.upolyPowmodSafe]
  simp only [Int.natCast_pos.mpr hn, if_pos, Int.toNat_natCast]
  refine ⟨hloop.1, hloop.2.trans ?_⟩
  rw [honedata.2, one_mul]
  exact pow_modByMonic_congr (by rw [hbdata.2, modByMonic_idem _ _ hm_monic]) n

/-- The total subtract-X entry point preserves canonical sparse form and has
the expected polynomial semantics. -/
private theorem upoly_subtract_x_safe_refines (h2p : 2 * p ≤ UInt64.size)
    (h : SparsePolyZp) (q : UInt64) (hq : q.toNat = p)
    (hh : CanonicalRep p h) :
    CanonicalRep p (Generated.upolySubtractXSafe h q) ∧
      SparsePolyZp.toPoly p (Generated.upolySubtractXSafe h q) =
        SparsePolyZp.toPoly p h - X := by
  have hx := singleton_x_data q hq
  rw [Generated.upolySubtractXSafe]
  refine ⟨canonicalRep_sub h _ hh hx.1, ?_⟩
  rw [SparsePolyZp.toPoly_sub p h2p h _ hh.2.2 hx.1.2.2, hx.2]

/-- Total DDF loop mirroring the generated control flow.  The defensive
`hdec` branch is unreachable under the refinement invariant and makes the
degree decrease explicit to Lean. -/
noncomputable def ddfZpLoopSafe (p : Nat) [Fact (Nat.Prime p)]
    (q : UInt64) (h fStar : SparsePolyZp) (d : Nat)
    (acc : Array (SparsePolyZp × UInt64)) :
    Array (SparsePolyZp × UInt64) :=
  if hterm : (SparsePolyZp.toPoly p fStar).natDegree < 2 * d then
    if 0 < (SparsePolyZp.toPoly p fStar).natDegree then
      acc.push (fStar, UInt64.ofNat (SparsePolyZp.toPoly p fStar).natDegree)
    else
      acc
  else
    let h' := Generated.upolyPowmodSafe Generated.__upoly_mod_ir h (q.toNat : Int) fStar
    let hMinusX := Generated.upolySubtractXSafe h' q
    let gd := polynomial_GCD hMinusX fStar
    if 0 < (SparsePolyZp.toPoly p gd).natDegree then
      let fNew := SparsePolyZp.normalization (SparsePolyZp.divmod fStar gd).1
      if hdec : (SparsePolyZp.toPoly p fNew).natDegree <
          (SparsePolyZp.toPoly p fStar).natDegree then
        let hNew := Generated.__upoly_mod_ir h' fNew
        ddfZpLoopSafe p q hNew fNew (d + 1)
          (acc.push (gd, UInt64.ofNat d))
      else
        acc
    else
      ddfZpLoopSafe p q h' fStar (d + 1) acc
termination_by (SparsePolyZp.toPoly p fStar).natDegree + 1 - 2 * d
decreasing_by
  · have hdec' : (SparsePolyZp.toPoly p
        (SparsePolyZp.normalization (SparsePolyZp.divmod fStar
          (polynomial_GCD
            (Generated.upolySubtractXSafe
              (Generated.upolyPowmodSafe Generated.__upoly_mod_ir h
                (q.toNat : Int) fStar) q) fStar)).1)).natDegree <
          (SparsePolyZp.toPoly p fStar).natDegree := by
      simpa only [fNew, gd, hMinusX, h'] using hdec
    omega
  · omega

noncomputable def ddfZpSafe (p : Nat) [Fact (Nat.Prime p)]
    (f : SparsePolyZp) : Array (SparsePolyZp × UInt64) :=
  if f.isEmpty then #[]
  else
    let q := (SparsePolyZp.front! f).snd.prime
    let x : SparsePolyZp := #[(UMonomial.mk (1 : Int32), Zp.ofInt (1 : Int) q)]
    ddfZpLoopSafe p q x f 1 #[]

set_option maxHeartbeats 0 in
private theorem ddfZpLoopSafe_refines (q : UInt64)
    (h fStar : SparsePolyZp) (d : Nat)
    (acc : Array (SparsePolyZp × UInt64))
    (h2p : 2 * p ≤ UInt64.size) (hp2 : p * p ≤ UInt64.size)
    (hq : q.toNat = p) (hd : 1 ≤ d)
    (hh : CanonicalRep p h) (hf : CanonicalRep p fStar)
    (hfmonic : Monic (SparsePolyZp.toPoly p fStar))
    (hfdeg : (SparsePolyZp.toPoly p fStar).natDegree < UInt64.size) :
    toPolyList (ddfZpLoopSafe p q h fStar d acc) p =
      ddfLoop (SparsePolyZp.toPoly p h) (SparsePolyZp.toPoly p fStar) d
        (toPolyList acc p) := by
  revert hq hd hh hf hfmonic hfdeg
  induction h, fStar, d, acc using ddfZpLoopSafe.induct p q
  case case1 h fStar d acc hterm hpos =>
    intro hq hd hh hf hfmonic hfdeg
    rw [ddfZpLoopSafe, dif_pos hterm, if_pos hpos]
    rw [ddfLoop, dif_pos hterm, if_pos hpos]
    simp [toPolyList, UInt64.toNat_ofNat_of_lt' hfdeg]
  case case2 h fStar d acc hterm hzero =>
    intro hq hd hh hf hfmonic hfdeg
    rw [ddfZpLoopSafe, dif_pos hterm, if_neg hzero]
    rw [ddfLoop, dif_pos hterm, if_neg hzero]
  case case3 h fStar d acc hterm h' hMinusX gd hsplit fNew hdec hNew ih =>
    intro hq hd hh hf hfmonic hfdeg
    have hfpos : 0 < (SparsePolyZp.toPoly p fStar).natDegree := by omega
    have hfpoly : SparsePolyZp.toPoly p fStar ≠ 0 := by
      intro hz
      simp [hz] at hfpos
    have hfne : ¬fStar.isEmpty :=
      nonempty_of_toPoly_ne_zero (p := p) fStar hfpoly
    have hfprime := front_prime_of_canonical fStar hf hfne
    have hpow := upoly_powmod_safe_refines h2p hp2 h fStar p hp.out.pos
      hh hf hfne hfmonic hfpos hfprime
    have hpow' : CanonicalRep p h' ∧
        SparsePolyZp.toPoly p h' =
          SparsePolyZp.toPoly p h ^ p %ₘ SparsePolyZp.toPoly p fStar := by
      simpa [h', hq] using hpow
    have hsub := upoly_subtract_x_safe_refines h2p h' q hq hpow'.1
    have hsub' : CanonicalRep p hMinusX ∧
        SparsePolyZp.toPoly p hMinusX = SparsePolyZp.toPoly p h' - X := by
      simpa [hMinusX] using hsub
    have hgcd := polynomial_GCD_step_data_right (p := p) h2p hp2
      hMinusX fStar hsub'.1 hf hfpoly
    have hgdcan : CanonicalRep p gd := by simpa [gd] using hgcd.1
    have hgdne : ¬gd.isEmpty := by simpa [gd] using hgcd.2.1
    have hgdpoly : SparsePolyZp.toPoly p gd = normalize (EuclideanDomain.gcd
        (SparsePolyZp.toPoly p h' - X) (SparsePolyZp.toPoly p fStar)) := by
      simpa [gd, hsub'.2] using hgcd.2.2.1
    have hgdmonic : Monic (SparsePolyZp.toPoly p gd) := by
      simpa [gd] using hgcd.2.2.2
    have hgddvd : SparsePolyZp.toPoly p gd ∣ SparsePolyZp.toPoly p fStar := by
      rw [hgdpoly]
      exact normalize_dvd_iff.mpr (EuclideanDomain.gcd_dvd_right _ _)
    let qRaw := (SparsePolyZp.divmod fStar gd).1
    have hqcan : CanonicalRep p qRaw :=
      divmod_fst_canonical fStar gd hf hgdcan hgdne h2p
    have hqpoly : SparsePolyZp.toPoly p qRaw =
        SparsePolyZp.toPoly p fStar /ₘ SparsePolyZp.toPoly p gd :=
      divmod_fst_toPoly_eq_divByMonic h2p hp2 fStar gd hf hgdcan hgdne
        hgdmonic hgddvd
    have hfnewcan : CanonicalRep p fNew := by
      simpa [fNew, qRaw] using normalization_canonical qRaw hqcan
    have hfnewpoly : SparsePolyZp.toPoly p fNew =
        SparsePolyZp.toPoly p fStar /ₘ SparsePolyZp.toPoly p gd := by
      simpa [fNew, qRaw, normalization_toPoly] using hqpoly
    have hmodzero : SparsePolyZp.toPoly p fStar %ₘ SparsePolyZp.toPoly p gd = 0 :=
      (modByMonic_eq_zero_iff_dvd hgdmonic).mpr hgddvd
    have hfactor : SparsePolyZp.toPoly p gd * SparsePolyZp.toPoly p fNew =
        SparsePolyZp.toPoly p fStar := by
      rw [hfnewpoly]
      have hadd := modByMonic_add_div (SparsePolyZp.toPoly p fStar)
        (SparsePolyZp.toPoly p gd)
      rw [hmodzero, zero_add] at hadd
      exact hadd
    have hfnewpoly0 : SparsePolyZp.toPoly p fNew ≠ 0 := by
      intro hz
      rw [hz, mul_zero] at hfactor
      exact hfpoly hfactor.symm
    have hfnewne : ¬fNew.isEmpty :=
      nonempty_of_toPoly_ne_zero (p := p) fNew hfnewpoly0
    have hfnewmonic : Monic (SparsePolyZp.toPoly p fNew) := by
      exact Polynomial.Monic.of_mul_monic_left hgdmonic (hfactor ▸ hfmonic)
    have hnewdata := upoly_mod_step_data h2p hp2 h' fNew hpow'.1 hfnewcan
      hfnewne hfnewmonic
    have hnewcan : CanonicalRep p hNew := by simpa [hNew] using hnewdata.1
    have hnewpoly : SparsePolyZp.toPoly p hNew =
        SparsePolyZp.toPoly p h' %ₘ SparsePolyZp.toPoly p fNew := by
      simpa [hNew] using hnewdata.2
    have hfnewdeg : (SparsePolyZp.toPoly p fNew).natDegree < UInt64.size :=
      lt_trans hdec hfdeg
    have hdsize : d < UInt64.size := by omega
    have ih' := ih hq (by omega) hnewcan hfnewcan hfnewmonic hfnewdeg
    rw [ddfZpLoopSafe, dif_neg hterm]
    dsimp only
    rw [if_pos hsplit, dif_pos hdec]
    conv_rhs =>
      rw [ddfLoop, dif_neg hterm]
      dsimp only
    have hsplitL2 : 0 < (normalize (EuclideanDomain.gcd
        (SparsePolyZp.toPoly p h ^ p %ₘ SparsePolyZp.toPoly p fStar - X)
        (SparsePolyZp.toPoly p fStar))).natDegree := by
      rw [← hpow'.2, ← hgdpoly]
      exact hsplit
    conv_rhs => rw [dif_pos hsplitL2]
    rw [ih']
    simp [toPolyList, UInt64.toNat_ofNat_of_lt' hdsize, hgdpoly,
      hfnewpoly, hnewpoly, hpow'.2]
  case case4 h fStar d acc hterm h' hMinusX gd hsplit fNew hdecneg =>
    intro hq hd hh hf hfmonic hfdeg
    have hfpos : 0 < (SparsePolyZp.toPoly p fStar).natDegree := by omega
    have hfpoly : SparsePolyZp.toPoly p fStar ≠ 0 := by
      intro hz
      simp [hz] at hfpos
    have hfne : ¬fStar.isEmpty :=
      nonempty_of_toPoly_ne_zero (p := p) fStar hfpoly
    have hfprime := front_prime_of_canonical fStar hf hfne
    have hpow := upoly_powmod_safe_refines h2p hp2 h fStar p hp.out.pos
      hh hf hfne hfmonic hfpos hfprime
    have hpow' : CanonicalRep p h' ∧
        SparsePolyZp.toPoly p h' =
          SparsePolyZp.toPoly p h ^ p %ₘ SparsePolyZp.toPoly p fStar := by
      simpa [h', hq] using hpow
    have hsub := upoly_subtract_x_safe_refines h2p h' q hq hpow'.1
    have hsub' : CanonicalRep p hMinusX ∧
        SparsePolyZp.toPoly p hMinusX = SparsePolyZp.toPoly p h' - X := by
      simpa [hMinusX] using hsub
    have hgcd := polynomial_GCD_step_data_right (p := p) h2p hp2
      hMinusX fStar hsub'.1 hf hfpoly
    have hgdcan : CanonicalRep p gd := by simpa [gd] using hgcd.1
    have hgdne : ¬gd.isEmpty := by simpa [gd] using hgcd.2.1
    have hgdpoly : SparsePolyZp.toPoly p gd = normalize (EuclideanDomain.gcd
        (SparsePolyZp.toPoly p h' - X) (SparsePolyZp.toPoly p fStar)) := by
      simpa [gd, hsub'.2] using hgcd.2.2.1
    have hgdmonic : Monic (SparsePolyZp.toPoly p gd) := by
      simpa [gd] using hgcd.2.2.2
    have hgddvd : SparsePolyZp.toPoly p gd ∣ SparsePolyZp.toPoly p fStar := by
      rw [hgdpoly]
      exact normalize_dvd_iff.mpr (EuclideanDomain.gcd_dvd_right _ _)
    let qRaw := (SparsePolyZp.divmod fStar gd).1
    have hqcan : CanonicalRep p qRaw :=
      divmod_fst_canonical fStar gd hf hgdcan hgdne h2p
    have hqpoly : SparsePolyZp.toPoly p qRaw =
        SparsePolyZp.toPoly p fStar /ₘ SparsePolyZp.toPoly p gd :=
      divmod_fst_toPoly_eq_divByMonic h2p hp2 fStar gd hf hgdcan hgdne
        hgdmonic hgddvd
    have hfnewpoly : SparsePolyZp.toPoly p fNew =
        SparsePolyZp.toPoly p fStar /ₘ SparsePolyZp.toPoly p gd := by
      simpa [fNew, qRaw, normalization_toPoly] using hqpoly
    have hmodzero : SparsePolyZp.toPoly p fStar %ₘ SparsePolyZp.toPoly p gd = 0 :=
      (modByMonic_eq_zero_iff_dvd hgdmonic).mpr hgddvd
    have hfactor : SparsePolyZp.toPoly p gd * SparsePolyZp.toPoly p fNew =
        SparsePolyZp.toPoly p fStar := by
      rw [hfnewpoly]
      have hadd := modByMonic_add_div (SparsePolyZp.toPoly p fStar)
        (SparsePolyZp.toPoly p gd)
      rw [hmodzero, zero_add] at hadd
      exact hadd
    have hfnewpoly0 : SparsePolyZp.toPoly p fNew ≠ 0 := by
      intro hz
      rw [hz, mul_zero] at hfactor
      exact hfpoly hfactor.symm
    have hdegmul := Polynomial.natDegree_mul hgdmonic.ne_zero hfnewpoly0
    rw [hfactor] at hdegmul
    have hdec : (SparsePolyZp.toPoly p fNew).natDegree <
        (SparsePolyZp.toPoly p fStar).natDegree := by omega
    exact absurd hdec hdecneg
  case case5 h fStar d acc hterm h' hMinusX gd hnosplit ih =>
    intro hq hd hh hf hfmonic hfdeg
    have hfpos : 0 < (SparsePolyZp.toPoly p fStar).natDegree := by omega
    have hfpoly : SparsePolyZp.toPoly p fStar ≠ 0 := by
      intro hz
      simp [hz] at hfpos
    have hfne : ¬fStar.isEmpty :=
      nonempty_of_toPoly_ne_zero (p := p) fStar hfpoly
    have hfprime := front_prime_of_canonical fStar hf hfne
    have hpow := upoly_powmod_safe_refines h2p hp2 h fStar p hp.out.pos
      hh hf hfne hfmonic hfpos hfprime
    have hpow' : CanonicalRep p h' ∧
        SparsePolyZp.toPoly p h' =
          SparsePolyZp.toPoly p h ^ p %ₘ SparsePolyZp.toPoly p fStar := by
      simpa [h', hq] using hpow
    have hsub := upoly_subtract_x_safe_refines h2p h' q hq hpow'.1
    have hsub' : CanonicalRep p hMinusX ∧
        SparsePolyZp.toPoly p hMinusX = SparsePolyZp.toPoly p h' - X := by
      simpa [hMinusX] using hsub
    have hgcd := polynomial_GCD_step_data_right (p := p) h2p hp2
      hMinusX fStar hsub'.1 hf hfpoly
    have hgdpoly : SparsePolyZp.toPoly p gd = normalize (EuclideanDomain.gcd
        (SparsePolyZp.toPoly p h' - X) (SparsePolyZp.toPoly p fStar)) := by
      simpa [gd, hsub'.2] using hgcd.2.2.1
    have hnsplitL2 : ¬0 < (normalize (EuclideanDomain.gcd
        (SparsePolyZp.toPoly p h' - X) (SparsePolyZp.toPoly p fStar))).natDegree := by
      simpa [hgdpoly] using hnosplit
    have hnsplitL2' : ¬0 < (normalize (EuclideanDomain.gcd
        (SparsePolyZp.toPoly p h ^ p %ₘ SparsePolyZp.toPoly p fStar - X)
        (SparsePolyZp.toPoly p fStar))).natDegree := by
      rw [← hpow'.2]
      exact hnsplitL2
    have ih' := ih hq (by omega) hpow'.1 hf hfmonic hfdeg
    rw [ddfZpLoopSafe, dif_neg hterm]
    dsimp only
    rw [if_neg hnosplit]
    conv_rhs =>
      rw [ddfLoop, dif_neg hterm]
      dsimp only
      rw [dif_neg hnsplitL2']
    rw [hpow'.2] at ih'
    exact ih'

/-- The total sparse DDF implementation refines the L2 DDF algorithm. -/
theorem ddfZpSafe_refines (p : Nat) [hp : Fact (Nat.Prime p)]
    (f : SparsePolyZp)
    (h2p : 2 * p ≤ UInt64.size) (hp2 : p * p ≤ UInt64.size)
    (hf : CanonicalRep p f) (hfmonic : Monic (SparsePolyZp.toPoly p f))
    (hfdeg : (SparsePolyZp.toPoly p f).natDegree < UInt64.size) :
    toPolyList (ddfZpSafe p f) p = ddf (SparsePolyZp.toPoly p f) := by
  have hfpoly : SparsePolyZp.toPoly p f ≠ 0 := hfmonic.ne_zero
  have hfne : ¬f.isEmpty := nonempty_of_toPoly_ne_zero (p := p) f hfpoly
  let q := (SparsePolyZp.front! f).snd.prime
  let x : SparsePolyZp :=
    #[(UMonomial.mk (1 : Int32), Zp.ofInt (1 : Int) q)]
  have hq : q.toNat = p := front_prime_of_canonical f hf hfne
  have hx := singleton_x_data q hq
  have hxpoly : SparsePolyZp.toPoly p x = X := by simpa [x] using hx.2
  have hloop := ddfZpLoopSafe_refines (p := p) q x f 1 #[] h2p hp2 hq
    (by omega) hx.1 hf hfmonic hfdeg
  unfold ddfZpSafe
  rw [if_neg hfne]
  dsimp only
  change toPolyList (ddfZpLoopSafe p q x f 1 #[]) p = _
  simpa [ddf, hxpoly] using hloop

end Refinement
