-- Auto-generated by cpp2lean v2 Pass 9 (refine_gen)
-- L1 → L2 refinement theorem skeletons

import CLPoly.Algorithm.DDF
import CLPoly.Model
import CLPoly.Generated.Corpus
import CLPoly.Refinement.Basic
import CLPoly.Refinement.SquarefreeZp
import CLPoly.Math.Univariate

set_option autoImplicit false

open Polynomial
open CLPoly.Math

namespace Refinement

variable {p : ℕ} [hp : Fact (Nat.Prime p)]

/-- `__upoly_mod_ir` 在规范输入上同时保持稀疏规范形，并精化为
mathlib 的首一多项式余式。 -/
private theorem upoly_mod_step_data (h2p : 2 * p ≤ UInt64.size)
    (hp2 : p * p ≤ UInt64.size) (f g : SparsePolyZp)
    (hf : CanonicalRep p f) (hg : CanonicalRep p g) (hg_ne : ¬g.isEmpty)
    (hg_monic : Monic (SparsePolyZp.toPoly p g)) :
    CanonicalRep p (Generated.__upoly_mod_ir f g) ∧
      SparsePolyZp.toPoly p (Generated.__upoly_mod_ir f g) =
        SparsePolyZp.toPoly p f %ₘ SparsePolyZp.toPoly p g := by
  have hmod := __upoly_mod_ir_refines p f g (wellFormed_of_canonical f hf) hf.2.2
    (wellFormed_of_canonical g hg) hg.2.2 h2p
  rw [hmod]
  exact ⟨divmod_snd_canonical f g hf hg hg_ne (by nlinarith),
    divmod_snd_toPoly_eq_modByMonic h2p hp2 f g hf hg hg_ne hg_monic⟩

/-- DDF/powmod 中的“先乘后取模”单步语义。 -/
private theorem mul_mod_step_data (h2p : 2 * p ≤ UInt64.size)
    (hp2 : p * p ≤ UInt64.size) (a b m : SparsePolyZp)
    (ha : CanonicalRep p a) (hb : CanonicalRep p b) (hm : CanonicalRep p m)
    (hm_ne : ¬m.isEmpty) (hm_monic : Monic (SparsePolyZp.toPoly p m)) :
    CanonicalRep p (Generated.__upoly_mod_ir (a * b) m) ∧
      SparsePolyZp.toPoly p (Generated.__upoly_mod_ir (a * b) m) =
        (SparsePolyZp.toPoly p a * SparsePolyZp.toPoly p b) %ₘ
          SparsePolyZp.toPoly p m := by
  have hab := canonicalRep_mul hp2 a b ha hb
  have hstep := upoly_mod_step_data h2p hp2 (a * b) m hab hm hm_ne hm_monic
  refine ⟨hstep.1, ?_⟩
  rw [hstep.2, SparsePolyZp.toPoly_mul p h2p hp2 a b ha.2.2 hb.2.2]

private lemma modByMonic_idem (a m : Polynomial (ZMod p)) (hm : Monic m) :
    (a %ₘ m) %ₘ m = a %ₘ m :=
  (modByMonic_eq_self_iff hm).mpr (degree_modByMonic_lt a hm)

private lemma mul_modByMonic_congr {a a' b b' m : Polynomial (ZMod p)}
    (ha : a %ₘ m = a' %ₘ m) (hb : b %ₘ m = b' %ₘ m) :
    (a * b) %ₘ m = (a' * b') %ₘ m := by
  calc
    (a * b) %ₘ m = (a %ₘ m) * (b %ₘ m) %ₘ m := Polynomial.mul_modByMonic _ _ _
    _ = (a' %ₘ m) * (b' %ₘ m) %ₘ m := by rw [ha, hb]
    _ = (a' * b') %ₘ m := (Polynomial.mul_modByMonic _ _ _).symm

private lemma pow_modByMonic_congr {a b m : Polynomial (ZMod p)}
    (h : a %ₘ m = b %ₘ m) : ∀ n : Nat, (a ^ n) %ₘ m = (b ^ n) %ₘ m := by
  intro n
  induction n with
  | zero => simp
  | succ n ih =>
      rw [pow_succ, pow_succ]
      exact mul_modByMonic_congr ih h

set_option maxHeartbeats 0 in
/-- 二进制 powmod 内循环在非负整数指数上的精确语义。 -/
private theorem powmod_loop_refines (h2p : 2 * p ≤ UInt64.size)
    (hp2 : p * p ≤ UInt64.size) (m : SparsePolyZp)
    (hm : CanonicalRep p m) (hm_ne : ¬m.isEmpty)
    (hm_monic : Monic (SparsePolyZp.toPoly p m)) :
    ∀ (n : Nat) (b r : SparsePolyZp),
      CanonicalRep p b → CanonicalRep p r →
      SparsePolyZp.toPoly p b %ₘ SparsePolyZp.toPoly p m = SparsePolyZp.toPoly p b →
      SparsePolyZp.toPoly p r %ₘ SparsePolyZp.toPoly p m = SparsePolyZp.toPoly p r →
      let out := Generated.upolyPowmodLoopSafe Generated.__upoly_mod_ir n b r m
      CanonicalRep p out ∧
        SparsePolyZp.toPoly p out =
          (SparsePolyZp.toPoly p r * SparsePolyZp.toPoly p b ^ n) %ₘ
            SparsePolyZp.toPoly p m := by
  intro n
  induction n using Nat.strongRecOn with
  | ind n ih =>
      intro b r hb hr hbmod hrmod
      by_cases hn : n = 0
      · subst n
        rw [Generated.upolyPowmodLoopSafe]
        simpa [hrmod]
      · have hnpos : 0 < n := Nat.pos_of_ne_zero hn
        let k := n / 2
        have hklt : k < n := Nat.div_lt_self hnpos (by norm_num)
        by_cases hodd : n % 2 ≠ 0
        · let r' := Generated.__upoly_mod_ir (r * b) m
          have hodd1 : n % 2 = 1 := by omega
          have hr'data := mul_mod_step_data h2p hp2 r b m hr hb hm hm_ne hm_monic
          have hr'can : CanonicalRep p r' := by simpa [r'] using hr'data.1
          have hr'poly : SparsePolyZp.toPoly p r' =
              (SparsePolyZp.toPoly p r * SparsePolyZp.toPoly p b) %ₘ
                SparsePolyZp.toPoly p m := by simpa [r'] using hr'data.2
          have hr'mod : SparsePolyZp.toPoly p r' %ₘ SparsePolyZp.toPoly p m =
              SparsePolyZp.toPoly p r' := by
            rw [hr'poly]
            exact modByMonic_idem _ _ hm_monic
          by_cases hkpos : 0 < k
          · let b' := Generated.__upoly_mod_ir (b * b) m
            have hb'data := mul_mod_step_data h2p hp2 b b m hb hb hm hm_ne hm_monic
            have hb'can : CanonicalRep p b' := by simpa [b'] using hb'data.1
            have hb'poly : SparsePolyZp.toPoly p b' =
                (SparsePolyZp.toPoly p b * SparsePolyZp.toPoly p b) %ₘ
                  SparsePolyZp.toPoly p m := by simpa [b'] using hb'data.2
            have hb'mod : SparsePolyZp.toPoly p b' %ₘ SparsePolyZp.toPoly p m =
                SparsePolyZp.toPoly p b' := by
              rw [hb'poly]
              exact modByMonic_idem _ _ hm_monic
            have hrec := ih k hklt b' r' hb'can hr'can hb'mod hr'mod
            rw [Generated.upolyPowmodLoopSafe]
            simp only [hnpos, if_pos, hodd, bne_iff_ne, ne_eq, k, hkpos]
            dsimp only at hrec ⊢
            refine ⟨hrec.1, hrec.2.trans ?_⟩
            have hnform : n = 2 * k + 1 := by omega
            calc
              (SparsePolyZp.toPoly p r' * SparsePolyZp.toPoly p b' ^ k) %ₘ
                  SparsePolyZp.toPoly p m =
                  ((SparsePolyZp.toPoly p r * SparsePolyZp.toPoly p b) *
                    (SparsePolyZp.toPoly p b * SparsePolyZp.toPoly p b) ^ k) %ₘ
                    SparsePolyZp.toPoly p m := mul_modByMonic_congr
                      (by rw [hr'poly, modByMonic_idem _ _ hm_monic])
                      (pow_modByMonic_congr
                        (by rw [hb'poly, modByMonic_idem _ _ hm_monic]) k)
              _ = (SparsePolyZp.toPoly p r * SparsePolyZp.toPoly p b ^ n) %ₘ
                    SparsePolyZp.toPoly p m := by rw [hnform]; congr 1 <;> ring
          · have hkzero : k = 0 := by omega
            rw [Generated.upolyPowmodLoopSafe]
            have hn_one : n = 1 := by omega
            subst n
            simpa [Generated.upolyPowmodLoopSafe] using hr'data
        · have heven : n % 2 = 0 := by omega
          have hkpos : 0 < k := by
            dsimp [k]
            omega
          let b' := Generated.__upoly_mod_ir (b * b) m
          have hb'data := mul_mod_step_data h2p hp2 b b m hb hb hm hm_ne hm_monic
          have hb'can : CanonicalRep p b' := by simpa [b'] using hb'data.1
          have hb'poly : SparsePolyZp.toPoly p b' =
              (SparsePolyZp.toPoly p b * SparsePolyZp.toPoly p b) %ₘ
                SparsePolyZp.toPoly p m := by simpa [b'] using hb'data.2
          have hb'mod : SparsePolyZp.toPoly p b' %ₘ SparsePolyZp.toPoly p m =
              SparsePolyZp.toPoly p b' := by
            rw [hb'poly]
            exact modByMonic_idem _ _ hm_monic
          have hrec := ih k hklt b' r hb'can hr hb'mod hrmod
          rw [Generated.upolyPowmodLoopSafe]
          simp only [hnpos, if_pos, heven, k, hkpos]
          dsimp only at hrec ⊢
          refine ⟨hrec.1, hrec.2.trans ?_⟩
          have hnform : n = 2 * k := by omega
          calc
            (SparsePolyZp.toPoly p r * SparsePolyZp.toPoly p b' ^ k) %ₘ
                SparsePolyZp.toPoly p m =
                (SparsePolyZp.toPoly p r *
                  (SparsePolyZp.toPoly p b * SparsePolyZp.toPoly p b) ^ k) %ₘ
                  SparsePolyZp.toPoly p m := mul_modByMonic_congr rfl
                    (pow_modByMonic_congr
                      (by rw [hb'poly, modByMonic_idem _ _ hm_monic]) k)
            _ = (SparsePolyZp.toPoly p r * SparsePolyZp.toPoly p b ^ n) %ₘ
                  SparsePolyZp.toPoly p m := by rw [hnform]; congr 1 <;> ring

/--
  L1 `__ddf_Zp_ir` (C++: `clpoly/polynomial_factorize_zp.hh`) → L2 `ddf`

  不同度数因子分解

  C++ source: `clpoly/polynomial_factorize_zp.hh` — Clang AST → cpp2lean v2 Pass 1-8 → Corpus.lean
  L2 model : Algorithm/DDF.lean — hand-written, proven correct
  Bridge   : SparsePolyZp.toPoly (see Math/Univariate.lean)

  Proof status: Skeleton (sorry) — fill to complete L1→L2 verification chain
-/
theorem __ddf_Zp_ir_refines (p : ℕ) [hp : Fact (Nat.Prime p)]
    (f : SparsePolyZp)
    (hwf_f : SparsePolyZp.WellFormed p f)
    (hred_f : SparsePolyZp.AllReduced p f.toList)
    (hp_size : 2 * p ≤ UInt64.size)
    :   toPolyList (Generated.__ddf_Zp_ir f) p = ddf (SparsePolyZp.toPoly p f) :=
  by
  sorry

end Refinement
