-- Auto-generated by cpp2lean v2 Pass 9 (refine_gen)
-- Do not edit: all completed public L1 → L2 contracts live here.

import CLPoly.Refinement.DDF
import CLPoly.Refinement.EDF
import CLPoly.Refinement.FactorZZ
import CLPoly.Refinement.FactorZp
import CLPoly.Refinement.Hensel
import CLPoly.Refinement.SelectPrime
import CLPoly.Refinement.StrictSquarefreeGenerated

set_option autoImplicit false
set_option linter.style.nameCheck false

open Polynomial
open CLPoly.Math

namespace Refinement

/-- Generated public contract for the original C++
`__select_prime` entry.  The strict L1 program uses well-founded machine-prime
enumeration and executes modular reduction, derivative/GCD, make-monic, DDF,
and EDF for every accepted candidate. -/
theorem __select_prime_raw_ir_refines_SelectionCorrect
    {State : Type} (engine : Generated.StrictEDF.RandomEngine State)
    (provider : StrictSelectPrime.CandidateRuntimeProvider engine)
    (initialRng : State) (useLargePrime : Bool) (f : SparsePolyZZ)
    (hinitialPrimeCorrect : Nat.Prime
      (if useLargePrime then
        ((18446744073709551615 : UInt64) - 58).toNat
      else (2 : UInt64).toNat))
    (hcanonical : StrictPolynomialMod.SparsePolyZZCanonical f)
    (hnonempty : 0 < f.size)
    (hdegree : 2 ≤ (SparsePolyZZ.toPoly f).natDegree)
    (hdegreeBound : (SparsePolyZZ.toPoly f).natDegree < 2 ^ 62)
    (hlcSemantic : ∀ p : UInt64, Nat.Prime p.toNat →
      ((SparsePolyZZ.front! f).2 : ZMod p.toNat) =
        ((SparsePolyZZ.toPoly f).leadingCoeff : ZMod p.toNat))
    (result : PrimeSelectionResult)
    (hrun : Generated.StrictSelectPrime.__select_prime_raw_ir
      (StrictSelectPrime.selectPrimeRawOps
        (StrictSelectPrime.concreteTryCandidate engine provider))
      (StrictSelectPrime.selectPrimeTermination
        (StrictSelectPrime.concreteTryCandidate engine provider))
      initialRng useLargePrime f = .ok result) :
    StrictSelectPrime.SelectionCorrect (SparsePolyZZ.toPoly f) result ∧
      StrictSelectPrime.SelectionPhysical result := by
  exact Refinement.StrictSelectPrime.__select_prime_raw_ir_refines engine provider initialRng useLargePrime f
    hinitialPrimeCorrect hcanonical hnonempty hdegree hdegreeBound
      hlcSemantic result hrun

/-- Generated public end-to-end contract for the original C++ `__factor_Zp`
entry.  Its executable side is the source-shaped strict L1 entry, including
make-monic, SQF, DDF, EDF, multiplicity attachment, RNG threading and the
`std::sort` permutation boundary. -/
theorem __factor_Zp_raw_ir_refines_FactorZpCorrect
    {State : Type} (engine : Generated.StrictEDF.RandomEngine State)
    (this : DenseUPolyZp) [Fact (Nat.Prime this._p.toNat)]
    (hcfg : CLPoly.Impl.StrictWordArithmetic.DensePreinvConfigured this)
    (sqfPhysical : StrictSquarefreeZp.YunRawGCDWorkspaceProvider this hcfg)
    (providers : StrictDDF.DDFRawProviders this)
    (termination : Generated.StrictEDF.EDFTermination
      (StrictEDF.strictEDFRawOps engine this providers))
    (sort : StrictFactorZp.SortByDegreeProvider) (initialRng : State)
    (f : SparsePolyZp)
    (hcanonical : SparsePolyZp.Canonical this._p.toNat f)
    (hnonempty : 0 < f.size)
    (hdegreePositive :
      0 < (SparsePolyZp.toPoly this._p.toNat f).natDegree)
    (hdegreeBound :
      (SparsePolyZp.toPoly this._p.toNat f).natDegree < 2 ^ 62) :
    let ops : Generated.StrictFactorZp.FactorZpRawOps State := {
      makeMonic := StrictSquarefreeZp.upolyMakeMonicIR this
      squarefree := StrictFactorZp.strictSQFCall this hcfg sqfPhysical
      ddf := StrictFactorZp.strictDDFCall this providers
      edf := StrictFactorZp.strictEDFCall engine this providers termination
      sortByDegree := sort.run }
    ∃ lc output,
      Generated.StrictFactorZp.__factor_Zp_raw_ir ops initialRng f =
        .ok (lc, output) ∧
      FactorZpCorrect (SparsePolyZp.toPoly this._p.toNat f)
        (Zp.toZMod this._p.toNat lc)
        (StrictFactorZp.factorResultToL2 this._p.toNat output) ∧
      (∀ item ∈ output.toList,
        SparsePolyZp.Canonical this._p.toNat item.1) := by
  exact Refinement.StrictFactorZp.__factor_Zp_raw_ir_refines_FactorZpCorrect engine this hcfg sqfPhysical providers termination
    sort initialRng f hcanonical hnonempty hdegreePositive hdegreeBound

/-- Generated public end-to-end contract for the original
C++ `__factor_squarefree_primitive_ZZ` entry.  Its executable side fixes the
actual generated prime-selection, modular factorization, quadratic Hensel
lifting, van-Hoeij/Zassenhaus recombination, and source branch structure. -/
theorem __factor_squarefree_primitive_ZZ_raw_ir_refines_FactorZZCorrect
    {State : Type} (engine : Generated.StrictEDF.RandomEngine State)
    (provider : StrictSelectPrime.CandidateRuntimeProvider engine)
    (initialRng : State) (useLargePrime : Bool) (f : SparsePolyZZ)
    (hinitialPrimeCorrect : Nat.Prime
      (if useLargePrime then
        ((18446744073709551615 : UInt64) - 58).toNat
      else (2 : UInt64).toNat))
    (hhenselInvariant : ∀ (selection : PrimeSelectionResult)
      (hp : Nat.Prime selection.prime.toNat) (aTarget : Int32),
      let candidate := provider.physical selection.prime hp
      @StrictFactorZZ.HenselLiftEntryReadiness candidate.dense
        StrictHensel.concreteDivmodTermination candidate.providers.mul
        f selection.factors aTarget)
    (hcanonical : StrictPolynomialMod.SparsePolyZZCanonical f)
    (hprimitive : (SparsePolyZZ.toPoly f).IsPrimitive)
    (hnonempty : 0 < f.size)
    (hdegree : 2 ≤ (SparsePolyZZ.toPoly f).natDegree)
    (hdegree62 : (SparsePolyZZ.toPoly f).natDegree < 2 ^ 62)
    (hdegree63 : f[0].1.deg < 2 ^ 63)
    (leading : UMonomial × ZZ) (hleading : f[0]? = some leading)
    (output : Array SparsePolyZZ)
    (hrun : Generated.StrictFactorZZ.__factor_squarefree_primitive_ZZ_raw_ir
      (StrictFactorZZ.concreteRecombineFactorZZRawOps
        (StrictFactorZZ.concreteSelectPrime engine provider initialRng)
        (StrictFactorZZ.concreteHenselLift engine provider))
      useLargePrime f = .ok output) :
    FactorZZCorrect (SparsePolyZZ.toPoly f)
      (output.toList.map SparsePolyZZ.toPoly) := by
  exact Refinement.StrictFactorZZ.concreteSelectHensel___factor_squarefree_primitive_ZZ_raw_ir_refines engine provider initialRng useLargePrime f
    hinitialPrimeCorrect hhenselInvariant hcanonical hprimitive hnonempty
      hdegree hdegree62 hdegree63 leading hleading output hrun

/-- Generated public contract for the original C++ `__squarefree_Zp` entry.
The executable side is the strict, well-founded L1 semantics; the result is
identified with the L2 `sqfZp` model. -/
theorem __squarefree_Zp_raw_ir_refines_sqfZp
    (this : DenseUPolyZp) [Fact (Nat.Prime this._p.toNat)]
    (hcfg : CLPoly.Impl.StrictWordArithmetic.DensePreinvConfigured this)
    (physical : StrictSquarefreeZp.YunRawGCDWorkspaceProvider this hcfg)
    (source : SparsePolyZp)
    (hcanonical : SparsePolyZp.Canonical this._p.toNat source)
    (hmonic : (SparsePolyZp.toPoly this._p.toNat source).Monic)
    (hnonempty : 0 < source.size)
    (hpositive : 0 < (SparsePolyZp.toPoly this._p.toNat source).natDegree)
    (hbound : CLPoly.Impl.StrictPolynomialGCDRefinement.sparseDenseLength source ≤ 2 ^ 63) :
    ∃ factors,
      Generated.StrictSquarefreeZp.__squarefree_Zp_raw_ir
          (StrictSquarefreeGenerated.strictSQFRawOps this hcfg physical)
          source (fun _ => ⟨hcanonical, hmonic, hnonempty, hpositive,
            hbound⟩) = .ok factors ∧
      toPolyList factors this._p.toNat =
        sqfZp (SparsePolyZp.toPoly this._p.toNat source) ∧
      ∀ item ∈ factors.toList,
        SparsePolyZp.Canonical this._p.toNat item.1 := by
  exact Refinement.StrictSquarefreeGenerated.__squarefree_Zp_raw_ir_refines_sqfZp this hcfg physical source hcanonical hmonic
    hnonempty hpositive hbound

/-- Generated public contract for the original C++ `__ddf_Zp` entry.
The executable side is the strict, well-founded L1 semantics; the result is
identified with the L2 `ddf` model. -/
theorem __ddf_Zp_raw_ir_refines_ddf
    (this : DenseUPolyZp) [Fact (Nat.Prime this._p.toNat)]
    (providers : StrictDDF.DDFRawProviders this) (f : SparsePolyZp)
    (hfPrime : f[0]!.2.prime = this._p)
    (hfCanonical : SparsePolyZp.Canonical this._p.toNat f)
    (hfDegree : ∀ term ∈ f.toList, term.1.deg < 2 ^ 62)
    (hfMonic : (SparsePolyZp.toPoly this._p.toNat f).Monic)
    (hfSquarefree : Squarefree (SparsePolyZp.toPoly this._p.toNat f)) :
    ∃ output,
      Generated.StrictDDF.__ddf_Zp_raw_ir
          (StrictDDF.strictDDFRawOps this providers
            (SparsePolyZp.toPoly this._p.toNat f)) f
          (fun _ => StrictDDF.DDFLoopInvariant.initial this f
            f[0]!.2.prime hfPrime
            hfCanonical hfDegree hfMonic hfSquarefree) = .ok output ∧
      StrictDDF.ddfResultToL2 this._p.toNat output =
        ddf (SparsePolyZp.toPoly this._p.toNat f) ∧
      (∀ item ∈ output.toList,
        SparsePolyZp.Canonical this._p.toNat item.1) ∧
      (∀ item ∈ output.toList,
        0 < (SparsePolyZp.toPoly this._p.toNat item.1).natDegree) ∧
      ∀ item ∈ output.toList, 0 < item.2.toNat := by
  exact Refinement.StrictDDF.strictDDFEntryIR_refines_ddf this providers f hfPrime
    hfCanonical hfDegree hfMonic hfSquarefree

/-- Generated public contract for the original C++ `__edf_Zp` entry.
The executable side is the strict, well-founded L1 semantics, including its
exact RNG transition; every newly appended concrete factor satisfies the L2
`EDFCorrect` specification. -/
theorem __edf_Zp_raw_ir_refines_edf
    {State : Type} (engine : Generated.StrictEDF.RandomEngine State)
    (this : DenseUPolyZp) [Fact (Nat.Prime this._p.toNat)]
    (providers : StrictDDF.DDFRawProviders this)
    (termination : Generated.StrictEDF.EDFTermination
      (StrictEDF.strictEDFRawOps engine this providers))
    (result : Array SparsePolyZp) (f : SparsePolyZp) (d : UInt64)
    (rng : State) (hinvariant : StrictEDF.EDFEntryInvariant this f d)
    (hresultCanonical : ∀ factor ∈ result.toList,
      SparsePolyZp.Canonical this._p.toNat factor) :
    ∃ output rng' factors,
      Generated.StrictEDF.__edf_Zp_raw_ir
          (StrictEDF.strictEDFRawOps engine this providers)
          (StrictEDF.strictEDFSplitLaw engine this providers) termination
          result f d rng hinvariant = .ok (output, rng') ∧
      StrictEDF.edfResultToL2 this._p.toNat output =
        StrictEDF.edfResultToL2 this._p.toNat result ++ factors ∧
      EDFCorrect (SparsePolyZp.toPoly this._p.toNat f) d.toNat factors ∧
      ∀ factor ∈ output.toList,
        SparsePolyZp.Canonical this._p.toNat factor := by
  exact Refinement.StrictEDF.strictEDFEntryIR_refines_edf engine this providers termination result f d rng
    hinvariant hresultCanonical

/-- Generated public contract for the polynomial extended
Euclidean entry used by Hensel tree construction. The executable side is the
strict degree-measured L1 loop, including generated division, inverse, and
terminal coefficient scaling; its first result is the L2 monic gcd and all
three concrete results satisfy the Bézout contract. -/
theorem __polynomial_GCD_eea_raw_ir_refines_gcd
    (this : DenseUPolyZp) [Fact (Nat.Prime this._p.toNat)]
    (hcfg : CLPoly.Impl.StrictWordArithmetic.DensePreinvConfigured this)
    (left right : SparsePolyZp)
    (hleftCanonical : SparsePolyZp.Canonical this._p.toNat left)
    (hrightCanonical : SparsePolyZp.Canonical this._p.toNat right)
    (hleftNonempty : 0 < left.size) :
    ∃ gcd s t,
      Generated.StrictHensel.__polynomial_GCD_eea_raw_ir
          (StrictHensel.strictHenselEEARawOps this)
          (StrictHensel.strictHenselEEATermination this)
          (Generated.StrictHensel.henselEEAInitialState this._p left right) =
        .ok (gcd, s, t) ∧
      SparsePolyZp.toPoly this._p.toNat gcd =
        SparsePolyZp.toPoly this._p.toNat s *
            SparsePolyZp.toPoly this._p.toNat left +
          SparsePolyZp.toPoly this._p.toNat t *
            SparsePolyZp.toPoly this._p.toNat right ∧
      (SparsePolyZp.toPoly this._p.toNat gcd).Monic ∧
      SparsePolyZp.toPoly this._p.toNat gcd ∣
        SparsePolyZp.toPoly this._p.toNat left ∧
      SparsePolyZp.toPoly this._p.toNat gcd ∣
        SparsePolyZp.toPoly this._p.toNat right ∧
      SparsePolyZp.toPoly this._p.toNat gcd =
        GCDMonoid.gcd
          (SparsePolyZp.toPoly this._p.toNat left)
          (SparsePolyZp.toPoly this._p.toNat right) := by
  exact Refinement.StrictHensel.strictHenselEEAEntryIR_refines_gcd this hcfg left right
    hleftCanonical hrightCanonical hleftNonempty

/-- Generated public contract for the original C++ `__hensel_step` entry.
The executable side is the exact strict raw L1 program, and its output
satisfies the L2 quadratic Hensel-step invariant without a model fallback. -/
theorem __hensel_step_raw_ir_refines
    (node : HenselNode) (f : SparsePolyZZ) (m : Nat)
    (hinvariant : StrictHensel.HenselStepRefinementInvariant
      StrictHensel.concreteDivmodTermination node f m) :
    ∃ output,
      Generated.StrictHensel.__hensel_step_raw_ir
          (StrictHensel.strictHenselRawOps
            StrictHensel.concreteDivmodTermination)
          node f (m : Int) = .ok output ∧
      StrictHensel.HenselStepCorrect f m node output := by
  exact Refinement.StrictHensel.__hensel_step_raw_ir_refines StrictHensel.concreteDivmodTermination node f m hinvariant

/-- Generated public contract for the original C++
`__hensel_lift_recursive` entry.  The executable side performs the exact
top-down raw tree traversal with structural well-founded recursion; its
semantic trace proves every concrete node update is a quadratic Hensel step. -/
theorem __hensel_lift_recursive_raw_ir_refines
    (tree : Generated.StrictHensel.HenselLiftTree)
    (nodes : Array HenselNode) (target : SparsePolyZZ) (m : Nat)
    (hinvariant : StrictHensel.HenselLiftRecursiveRefinementInvariant
      StrictHensel.concreteDivmodTermination tree nodes target m) :
    ∃ output,
      Generated.StrictHensel.__hensel_lift_recursive_raw_ir
          (StrictHensel.strictHenselRawOps
            StrictHensel.concreteDivmodTermination)
          tree nodes target (m : Int) = .ok output ∧
      StrictHensel.HenselLiftRecursiveCorrect
        StrictHensel.concreteDivmodTermination m tree nodes target output := by
  exact Refinement.StrictHensel.__hensel_lift_recursive_raw_ir_refines StrictHensel.concreteDivmodTermination tree nodes target m hinvariant

/-- Generated public contract for the original C++
`__hensel_extract_factors` entry.  The executable side performs the exact
left-before-right traversal of the concrete Hensel tree; its semantic trace
records precisely which leaf factors are appended to the input array. -/
theorem __hensel_extract_factors_raw_ir_refines
    (tree : Generated.StrictHensel.HenselLiftTree)
    (nodes : Array HenselNode) (factors : Array SparsePolyZZ)
    (hinvariant : StrictHensel.HenselExtractInvariant tree nodes) :
    ∃ output,
      Generated.StrictHensel.__hensel_extract_factors_raw_ir
          tree nodes factors = .ok output ∧
      StrictHensel.HenselExtractCorrect tree nodes factors output := by
  exact Refinement.StrictHensel.__hensel_extract_factors_raw_ir_refines tree nodes factors hinvariant

/-- Generated public contract for the original C++
`__hensel_tree_build` entry. The actual strict raw builder allocates exactly
the canonical preorder topology and produces the invariant consumed by the
generated extraction traversal; no mathematical tree is supplied as an
oracle. -/
theorem __hensel_tree_build_raw_ir_refines
    (this : DenseUPolyZp) [Fact (Nat.Prime this._p.toNat)]
    (hcfg : CLPoly.Impl.StrictWordArithmetic.DensePreinvConfigured this)
    (mulProvider : StrictDDF.RawMulWorkspaceProvider this)
    (factors : Array SparsePolyZp)
    (hfactors : ∀ factor ∈ factors.toList,
      SparsePolyZp.Canonical this._p.toNat factor)
    (hfactorsNonempty : ∀ factor ∈ factors.toList, 0 < factor.size)
    (hfactorsMonicAfterZero : ∀ index (hindex : index < factors.size),
      0 < index → (SparsePolyZp.toPoly this._p.toNat
        (getElem factors index hindex)).Monic)
    (hpairwise : ∀ i j (hi : i < factors.size) (hj : j < factors.size),
      i < j → IsCoprime
        (SparsePolyZp.toPoly this._p.toNat (getElem factors i hi))
        (SparsePolyZp.toPoly this._p.toNat (getElem factors j hj)))
    (htwo : 2 ≤ factors.size)
    (hfactorFits : factors.size < 2 ^ 31)
    (hfitsInt32 : StrictHensel.henselTreeInternalNodeCount
      0 factors.size < 2 ^ 31) :
    let tree := StrictHensel.henselTreeBuildTopology 0 factors.size 0
    ∃ output,
      Generated.StrictHensel.__hensel_tree_build_raw_ir
          (StrictHensel.strictHenselTreeBuildRawOps this mulProvider)
          factors this._p = .ok output ∧
      ∃ hroot : 0 < output.size,
      output.size = tree.nodeCount ∧ tree.rootIndex = 0 ∧
      StrictHensel.liftChildMatches (getElem output 0 hroot).left
        (match tree with | .node _ left _ => left) ∧
      StrictHensel.liftChildMatches (getElem output 0 hroot).right
        (match tree with | .node _ _ right => right) ∧
      StrictHensel.HenselExtractInvariant tree output ∧
      StrictHensel.HenselTreeSemanticBuildCertificate this._p.toNat factors 0
        0 factors.size tree output ∧
      StrictHensel.HenselTreeNodeInitialInvariant this._p.toNat factors
        0 factors.size (getElem output 0 hroot) ∧
      StrictHensel.HenselArrayCanonical output ∧
      StrictHensel.HenselArrayHOneHead output := by
  exact Refinement.StrictHensel.strictHenselTreeBuildRawIR_refines_topology_root this hcfg mulProvider factors hfactors
    hfactorsNonempty hfactorsMonicAfterZero hpairwise htwo hfactorFits
      hfitsInt32

/-- Generated public contract for the original C++
`__hensel_lift_upoly` entry.  The strict generated L1 program executes target
selection, coefficient adjustment, tree construction, quadratic lifting,
leaf extraction, and normalization; the L2 trace records every actual stage
result without an oracle, fallback, or fuel parameter. -/
theorem __hensel_lift_upoly_raw_ir_refines
    (this : DenseUPolyZp) [Fact (Nat.Prime this._p.toNat)]
    (hcfg : CLPoly.Impl.StrictWordArithmetic.DensePreinvConfigured this)
    (mulProvider : StrictDDF.RawMulWorkspaceProvider this)
    (f : SparsePolyZZ) (factors : Array SparsePolyZp) (aTarget : Int32)
    (hinvariant : StrictHensel.HenselLiftEntryInvariant this
      StrictHensel.concreteDivmodTermination mulProvider f factors aTarget)
    (hfactorCount : 2 ≤ factors.size)
    (hfactorFits : factors.size < 2 ^ 31) :
    ∃ output,
      Generated.StrictHensel.__hensel_lift_upoly_raw_ir
          (StrictHensel.strictHenselRawOps
            StrictHensel.concreteDivmodTermination)
          (StrictHensel.strictHenselTreeBuildRawOps this mulProvider)
          f factors this._p aTarget
            (Nat.Prime.two_le (Fact.out : Nat.Prime this._p.toNat)) =
              .ok output ∧
      StrictHensel.HenselLiftEntryCorrect
        StrictHensel.concreteDivmodTermination f factors this._p aTarget
        output := by
  exact Refinement.StrictHensel.__hensel_lift_upoly_raw_ir_refines this hcfg
    StrictHensel.concreteDivmodTermination mulProvider f factors aTarget
      hinvariant hfactorCount hfactorFits

end Refinement
