-- Auto-generated by cpp2lean v2 Pass 9 (refine_gen)
-- Do not edit: all completed public L1 → L2 contracts live here.

import CLPoly.Refinement.DDF
import CLPoly.Refinement.EDF
import CLPoly.Refinement.Hensel
import CLPoly.Refinement.StrictSquarefreeGenerated

set_option autoImplicit false
set_option linter.style.nameCheck false

open Polynomial
open CLPoly.Math

namespace Refinement

/-- Generated public contract for the original C++ `__squarefree_Zp` entry.
The executable side is the strict, well-founded L1 semantics; the result is
identified with the L2 `sqfZp` model. -/
theorem __squarefree_Zp_raw_ir_refines_sqfZp
    (this : DenseUPolyZp) [Fact (Nat.Prime this._p.toNat)]
    (hcfg : CLPoly.Impl.StrictWordArithmetic.DensePreinvConfigured this)
    (physical : StrictSquarefreeZp.YunRawGCDWorkspaceProvider this hcfg)
    (source : SparsePolyZp)
    (hcanonical : SparsePolyZp.Canonical this._p.toNat source)
    (hmonic : (SparsePolyZp.toPoly this._p.toNat source).Monic)
    (hnonempty : 0 < source.size)
    (hpositive : 0 < (SparsePolyZp.toPoly this._p.toNat source).natDegree)
    (hbound : CLPoly.Impl.StrictPolynomialGCDRefinement.sparseDenseLength source ≤ 2 ^ 63) :
    ∃ factors,
      Generated.StrictSquarefreeZp.__squarefree_Zp_raw_ir
          (StrictSquarefreeGenerated.strictSQFRawOps this hcfg physical)
          source (fun _ => ⟨hcanonical, hmonic, hnonempty, hpositive,
            hbound⟩) = .ok factors ∧
      toPolyList factors this._p.toNat =
        sqfZp (SparsePolyZp.toPoly this._p.toNat source) ∧
      ∀ item ∈ factors.toList,
        SparsePolyZp.Canonical this._p.toNat item.1 := by
  exact Refinement.StrictSquarefreeGenerated.__squarefree_Zp_raw_ir_refines_sqfZp this hcfg physical source hcanonical hmonic
    hnonempty hpositive hbound

/-- Generated public contract for the original C++ `__ddf_Zp` entry.
The executable side is the strict, well-founded L1 semantics; the result is
identified with the L2 `ddf` model. -/
theorem __ddf_Zp_raw_ir_refines_ddf
    (this : DenseUPolyZp) [Fact (Nat.Prime this._p.toNat)]
    (providers : StrictDDF.DDFRawProviders this) (f : SparsePolyZp)
    (hfPrime : f[0]!.2.prime = this._p)
    (hfCanonical : SparsePolyZp.Canonical this._p.toNat f)
    (hfDegree : ∀ term ∈ f.toList, term.1.deg < 2 ^ 62)
    (hfMonic : (SparsePolyZp.toPoly this._p.toNat f).Monic)
    (hfSquarefree : Squarefree (SparsePolyZp.toPoly this._p.toNat f)) :
    ∃ output,
      Generated.StrictDDF.__ddf_Zp_raw_ir
          (StrictDDF.strictDDFRawOps this providers
            (SparsePolyZp.toPoly this._p.toNat f)) f
          (fun _ => StrictDDF.DDFLoopInvariant.initial this f
            f[0]!.2.prime hfPrime
            hfCanonical hfDegree hfMonic hfSquarefree) = .ok output ∧
      StrictDDF.ddfResultToL2 this._p.toNat output =
        ddf (SparsePolyZp.toPoly this._p.toNat f) ∧
      (∀ item ∈ output.toList,
        SparsePolyZp.Canonical this._p.toNat item.1) ∧
      (∀ item ∈ output.toList,
        0 < (SparsePolyZp.toPoly this._p.toNat item.1).natDegree) ∧
      ∀ item ∈ output.toList, 0 < item.2.toNat := by
  exact Refinement.StrictDDF.strictDDFEntryIR_refines_ddf this providers f hfPrime
    hfCanonical hfDegree hfMonic hfSquarefree

/-- Generated public contract for the original C++ `__edf_Zp` entry.
The executable side is the strict, well-founded L1 semantics, including its
exact RNG transition; every newly appended concrete factor satisfies the L2
`EDFCorrect` specification. -/
theorem __edf_Zp_raw_ir_refines_edf
    {State : Type} (engine : Generated.StrictEDF.RandomEngine State)
    (this : DenseUPolyZp) [Fact (Nat.Prime this._p.toNat)]
    (providers : StrictDDF.DDFRawProviders this)
    (termination : Generated.StrictEDF.EDFTermination
      (StrictEDF.strictEDFRawOps engine this providers))
    (result : Array SparsePolyZp) (f : SparsePolyZp) (d : UInt64)
    (rng : State) (hinvariant : StrictEDF.EDFEntryInvariant this f d) :
    ∃ output rng' factors,
      Generated.StrictEDF.__edf_Zp_raw_ir
          (StrictEDF.strictEDFRawOps engine this providers)
          (StrictEDF.strictEDFSplitLaw engine this providers) termination
          result f d rng hinvariant = .ok (output, rng') ∧
      StrictEDF.edfResultToL2 this._p.toNat output =
        StrictEDF.edfResultToL2 this._p.toNat result ++ factors ∧
      EDFCorrect (SparsePolyZp.toPoly this._p.toNat f) d.toNat factors := by
  exact Refinement.StrictEDF.strictEDFEntryIR_refines_edf engine this providers termination result f d rng
    hinvariant

/-- Generated public contract for the polynomial extended
Euclidean entry used by Hensel tree construction. The executable side is the
strict degree-measured L1 loop, including generated division, inverse, and
terminal coefficient scaling; its first result is the L2 monic gcd and all
three concrete results satisfy the Bézout contract. -/
theorem __polynomial_GCD_eea_raw_ir_refines_gcd
    (this : DenseUPolyZp) [Fact (Nat.Prime this._p.toNat)]
    (hcfg : CLPoly.Impl.StrictWordArithmetic.DensePreinvConfigured this)
    (h2p : 2 * this._p.toNat ≤ UInt64.size)
    (hp2 : this._p.toNat * this._p.toNat ≤ UInt64.size)
    (left right : SparsePolyZp)
    (hleftCanonical : SparsePolyZp.Canonical this._p.toNat left)
    (hrightCanonical : SparsePolyZp.Canonical this._p.toNat right)
    (hleftNonempty : 0 < left.size) :
    ∃ gcd s t,
      Generated.StrictHensel.__polynomial_GCD_eea_raw_ir
          (StrictHensel.strictHenselEEARawOps this)
          (StrictHensel.strictHenselEEATermination this)
          (Generated.StrictHensel.henselEEAInitialState this._p left right) =
        .ok (gcd, s, t) ∧
      SparsePolyZp.toPoly this._p.toNat gcd =
        SparsePolyZp.toPoly this._p.toNat s *
            SparsePolyZp.toPoly this._p.toNat left +
          SparsePolyZp.toPoly this._p.toNat t *
            SparsePolyZp.toPoly this._p.toNat right ∧
      (SparsePolyZp.toPoly this._p.toNat gcd).Monic ∧
      SparsePolyZp.toPoly this._p.toNat gcd ∣
        SparsePolyZp.toPoly this._p.toNat left ∧
      SparsePolyZp.toPoly this._p.toNat gcd ∣
        SparsePolyZp.toPoly this._p.toNat right ∧
      SparsePolyZp.toPoly this._p.toNat gcd =
        GCDMonoid.gcd
          (SparsePolyZp.toPoly this._p.toNat left)
          (SparsePolyZp.toPoly this._p.toNat right) := by
  exact Refinement.StrictHensel.strictHenselEEAEntryIR_refines_gcd this hcfg h2p hp2 left right
    hleftCanonical hrightCanonical hleftNonempty

/-- Generated public contract for the original C++ `__hensel_step` entry.
The executable side is the exact strict raw L1 program, and its output
satisfies the L2 quadratic Hensel-step invariant without a model fallback. -/
theorem __hensel_step_raw_ir_refines
    (termination : Generated.StrictHensel.DivmodTermination)
    (node : HenselNode) (f : SparsePolyZZ) (m : Nat)
    (hinvariant : StrictHensel.HenselStepRefinementInvariant
      termination node f m) :
    ∃ output,
      Generated.StrictHensel.__hensel_step_raw_ir
          (StrictHensel.strictHenselRawOps termination)
          node f (m : Int) = .ok output ∧
      StrictHensel.HenselStepCorrect f m node output := by
  exact Refinement.StrictHensel.__hensel_step_raw_ir_refines termination node f m hinvariant

/-- Generated public contract for the original C++
`__hensel_lift_recursive` entry.  The executable side performs the exact
top-down raw tree traversal with structural well-founded recursion; its
semantic trace proves every concrete node update is a quadratic Hensel step. -/
theorem __hensel_lift_recursive_raw_ir_refines
    (termination : Generated.StrictHensel.DivmodTermination)
    (tree : Generated.StrictHensel.HenselLiftTree)
    (nodes : Array HenselNode) (target : SparsePolyZZ) (m : Nat)
    (hinvariant : StrictHensel.HenselLiftRecursiveRefinementInvariant
      termination tree nodes target m) :
    ∃ output,
      Generated.StrictHensel.__hensel_lift_recursive_raw_ir
          (StrictHensel.strictHenselRawOps termination)
          tree nodes target (m : Int) = .ok output ∧
      StrictHensel.HenselLiftRecursiveCorrect termination m tree nodes target
        output := by
  exact Refinement.StrictHensel.__hensel_lift_recursive_raw_ir_refines termination tree nodes target m hinvariant

/-- Generated public contract for the original C++
`__hensel_extract_factors` entry.  The executable side performs the exact
left-before-right traversal of the concrete Hensel tree; its semantic trace
records precisely which leaf factors are appended to the input array. -/
theorem __hensel_extract_factors_raw_ir_refines
    (tree : Generated.StrictHensel.HenselLiftTree)
    (nodes : Array HenselNode) (factors : Array SparsePolyZZ)
    (hinvariant : StrictHensel.HenselExtractInvariant tree nodes) :
    ∃ output,
      Generated.StrictHensel.__hensel_extract_factors_raw_ir
          tree nodes factors = .ok output ∧
      StrictHensel.HenselExtractCorrect tree nodes factors output := by
  exact Refinement.StrictHensel.__hensel_extract_factors_raw_ir_refines tree nodes factors hinvariant

end Refinement
