-- Auto-generated by cpp2lean v2 Pass 9 (refine_gen)
-- Do not edit: all completed public L1 → L2 contracts live here.

import CLPoly.Refinement.DDF
import CLPoly.Refinement.StrictSquarefreeGenerated

set_option autoImplicit false
set_option linter.style.nameCheck false

open Polynomial
open CLPoly.Math

namespace Refinement

/-- Generated public contract for the original C++ `__squarefree_Zp` entry.
The executable side is the strict, well-founded L1 semantics; the result is
identified with the L2 `sqfZp` model. -/
theorem __squarefree_Zp_raw_ir_refines_sqfZp
    (this : DenseUPolyZp) [Fact (Nat.Prime this._p.toNat)]
    (hcfg : CLPoly.Impl.StrictWordArithmetic.DensePreinvConfigured this)
    (physical : StrictSquarefreeZp.YunRawGCDWorkspaceProvider this hcfg)
    (source : SparsePolyZp)
    (hcanonical : SparsePolyZp.Canonical this._p.toNat source)
    (hmonic : (SparsePolyZp.toPoly this._p.toNat source).Monic)
    (hnonempty : 0 < source.size)
    (hpositive : 0 < (SparsePolyZp.toPoly this._p.toNat source).natDegree)
    (hbound : CLPoly.Impl.StrictPolynomialGCDRefinement.sparseDenseLength source ≤ 2 ^ 63) :
    ∃ factors,
      Generated.StrictSquarefreeZp.__squarefree_Zp_raw_ir
          (StrictSquarefreeGenerated.strictSQFRawOps this hcfg physical)
          source (fun _ => ⟨hcanonical, hmonic, hnonempty, hpositive,
            hbound⟩) = .ok factors ∧
      toPolyList factors this._p.toNat =
        sqfZp (SparsePolyZp.toPoly this._p.toNat source) := by
  exact Refinement.StrictSquarefreeGenerated.__squarefree_Zp_raw_ir_refines_sqfZp this hcfg physical source hcanonical hmonic
    hnonempty hpositive hbound

/-- Generated public contract for the original C++ `__ddf_Zp` entry.
The executable side is the strict, well-founded L1 semantics; the result is
identified with the L2 `ddf` model. -/
theorem __ddf_Zp_raw_ir_refines_ddf
    (this : DenseUPolyZp) [Fact (Nat.Prime this._p.toNat)]
    (providers : StrictDDF.DDFRawProviders this) (f : SparsePolyZp)
    (hfPrime : f[0]!.2.prime = this._p)
    (hfCanonical : SparsePolyZp.Canonical this._p.toNat f)
    (hfDegree : ∀ term ∈ f.toList, term.1.deg < 2 ^ 62)
    (hfMonic : (SparsePolyZp.toPoly this._p.toNat f).Monic)
    (hfSquarefree : Squarefree (SparsePolyZp.toPoly this._p.toNat f)) :
    ∃ output,
      Generated.StrictDDF.__ddf_Zp_raw_ir
          (StrictDDF.strictDDFRawOps this providers
            (SparsePolyZp.toPoly this._p.toNat f)) f
          (fun _ => StrictDDF.DDFLoopInvariant.initial this f
            f[0]!.2.prime hfPrime
            hfCanonical hfDegree hfMonic hfSquarefree) = .ok output ∧
      StrictDDF.ddfResultToL2 this._p.toNat output =
        ddf (SparsePolyZp.toPoly this._p.toNat f) := by
  exact Refinement.StrictDDF.strictDDFEntryIR_refines_ddf this providers f hfPrime
    hfCanonical hfDegree hfMonic hfSquarefree

end Refinement
