-- Auto-generated by cpp2lean v2 Pass 9 (refine_gen)
-- L1 → L2 refinement theorem skeletons

import CLPoly.Algorithm.SquarefreeZp
import CLPoly.Model
import CLPoly.Generated.Corpus
import CLPoly.Refinement.Basic
import CLPoly.Math.Univariate

set_option autoImplicit false

open Polynomial
open CLPoly.Math

namespace Refinement

variable {p : ℕ} [hp : Fact (Nat.Prime p)]

/--
  L1 `__squarefree_Zp_ir` (C++: `clpoly/polynomial_factorize_zp.hh`) → L2 `sqfZp`

  无平方因子分解（Yun 算法）

  C++ source: `clpoly/polynomial_factorize_zp.hh` — Clang AST → cpp2lean v2 Pass 1-8 → Corpus.lean
  L2 model : Algorithm/SquarefreeZp.lean — hand-written, proven correct
  Bridge   : SparsePolyZp.toPoly (see Math/Univariate.lean)

  Proof status: Skeleton (sorry) — fill to complete L1→L2 verification chain
-/
theorem __squarefree_Zp_ir_refines (p : ℕ) [hp : Fact (Nat.Prime p)]
    (f : SparsePolyZp)
    (hwf_f : SparsePolyZp.WellFormed p f)
    (hred_f : SparsePolyZp.AllReduced p f.toList)
    (hp_size : 2 * p ≤ UInt64.size)
    :   toPolyList (Generated.__squarefree_Zp_ir f) p = sqfZp (SparsePolyZp.toPoly p f) :=
  by
  sorry

end Refinement
