-- Auto-generated by cpp2lean v2 Pass 9 (refine_gen)
-- L1 → L2 refinement theorem skeletons

import CLPoly.Model
import CLPoly.Model
import CLPoly.Generated.Corpus
import CLPoly.Refinement.Basic
import CLPoly.Math.Univariate

set_option autoImplicit false

open Polynomial
open CLPoly.Math

namespace Refinement

variable {p : ℕ} [hp : Fact (Nat.Prime p)]

/--
  L1 `__make_zp_ir` (C++: `clpoly/number/ZZ.hh`) → L2 `Zp.ofInt`

  Zp 构造函数

  C++ source: `clpoly/number/ZZ.hh` — Clang AST → cpp2lean v2 Pass 1-8 → Corpus.lean
  L2 model : Algorithm/ZpArith.lean — hand-written, proven correct
  Bridge   : SparsePolyZp.toPoly (see Math/Univariate.lean)

  Proof status: Skeleton (sorry) — fill to complete L1→L2 verification chain
-/
theorem __make_zp_ir_refines (p : ℕ) [hp : Fact (Nat.Prime p)]
    (val : Int64)
    (modulus : UInt64)
    :   Generated.__make_zp_ir val modulus = Zp.ofInt val.toInt modulus :=
  rfl

/--
  L1 `__upoly_make_monic_ir` (C++: `clpoly/upolynomial.hh`) → L2 `SparsePolyZp.makeMonic`

  首一化：multiply by inv(lc)

  C++ source: `clpoly/upolynomial.hh` — Clang AST → cpp2lean v2 Pass 1-8 → Corpus.lean
  L2 model : Algorithm/ZpArith.lean — hand-written, proven correct
  Bridge   : SparsePolyZp.toPoly (see Math/Univariate.lean)

  Proof status: Skeleton (sorry) — fill to complete L1→L2 verification chain
-/
theorem __upoly_make_monic_ir_refines (p : ℕ) [hp : Fact (Nat.Prime p)]
    (f : SparsePolyZp)
    (hwf_f : SparsePolyZp.WellFormed p f)
    (hred_f : SparsePolyZp.AllReduced p f.toList)
    (hp_size : 2 * p ≤ UInt64.size)
    :   SparsePolyZp.toPoly p (Generated.__upoly_make_monic_ir f).snd = SparsePolyZp.toPoly p (SparsePolyZp.makeMonic f) :=
by
  by_cases hempty : f.isEmpty
  · simp [hempty, Generated.__upoly_make_monic_ir, SparsePolyZp.makeMonic, SparsePolyZp.toPoly_empty p]
  · have h_nonempty : ¬ f.isEmpty := hempty
    have h_pos : 0 < Array.size f := Array.size_pos_of_nonempty h_nonempty
    unfold Generated.__upoly_make_monic_ir SparsePolyZp.makeMonic
    let lc := (SparsePolyZp.front! f).snd
    have hlc_prime : lc.prime.toNat = p := hwf_f _ (by
      -- need to show (SparsePolyZp.front! f) ∈ f
      have : (SparsePolyZp.front! f) ∈ f := by
        simpa [SparsePolyZp.front!, Array.mem_iff_get] using h_pos
      exact this)
    have hlc_val_lt_p : lc.val.toNat < p := hred_f _ (by
      have : (SparsePolyZp.front! f) ∈ f := by
        simpa [SparsePolyZp.front!, Array.mem_iff_get] using h_pos
      exact this)
    by_cases hone : lc.val = (1 : UInt64)
    · simp [hone]
    · have h_lc_inv := Zp.inv lc
      sorry
      -- TODO: finish the proof by showing loop result = scalarMul lc_inv f under toPoly
      sorry

/--
  L1 `__upoly_divmod_ir` (C++: `clpoly/upolynomial.hh`) → L2 `SparsePolyZp.divmod`

  多项式长除法：q = f / g, r = f mod g

  C++ source: `clpoly/upolynomial.hh` — Clang AST → cpp2lean v2 Pass 1-8 → Corpus.lean
  L2 model : Algorithm/ZpArith.lean — hand-written, proven correct
  Bridge   : SparsePolyZp.toPoly (see Math/Univariate.lean)

  Proof status: Skeleton (sorry) — fill to complete L1→L2 verification chain
-/
theorem __upoly_divmod_ir_refines (p : ℕ) [hp : Fact (Nat.Prime p)]
    (q : SparsePolyZp)
    (r : SparsePolyZp)
    (f : SparsePolyZp)
    (g : SparsePolyZp)
    (hwf_q : SparsePolyZp.WellFormed p q)
    (hred_q : SparsePolyZp.AllReduced p q.toList)
    (hwf_r : SparsePolyZp.WellFormed p r)
    (hred_r : SparsePolyZp.AllReduced p r.toList)
    (hwf_f : SparsePolyZp.WellFormed p f)
    (hred_f : SparsePolyZp.AllReduced p f.toList)
    (hwf_g : SparsePolyZp.WellFormed p g)
    (hred_g : SparsePolyZp.AllReduced p g.toList)
    (hp_size : 2 * p ≤ UInt64.size)
    :   SparsePolyZp.toPoly p (Generated.__upoly_divmod_ir q r f g).1 = SparsePolyZp.toPoly p (SparsePolyZp.divmod f g).1 ∧
  SparsePolyZp.toPoly p (Generated.__upoly_divmod_ir q r f g).2 = SparsePolyZp.toPoly p (SparsePolyZp.divmod f g).2 :=
  by
  unfold Generated.__upoly_divmod_ir pair_vec_div5
  have h : HasPolyDivmod.polyDivmod (α := SparsePolyZp) = SparsePolyZp.divmod := rfl
  simp [h]

/--
  L1 `__upoly_mod_ir` (C++: `clpoly/upolynomial.hh`) → L2 `SparsePolyZp.divmod`

  多项式取模 remainder = f mod g

  C++ source: `clpoly/upolynomial.hh` — Clang AST → cpp2lean v2 Pass 1-8 → Corpus.lean
  L2 model : Algorithm/ZpArith.lean — hand-written, proven correct
  Bridge   : SparsePolyZp.toPoly (see Math/Univariate.lean)

  Proof status: Skeleton (sorry) — fill to complete L1→L2 verification chain
-/
theorem __upoly_mod_ir_refines (p : ℕ) [hp : Fact (Nat.Prime p)]
    (f : SparsePolyZp)
    (g : SparsePolyZp)
    (hwf_f : SparsePolyZp.WellFormed p f)
    (hred_f : SparsePolyZp.AllReduced p f.toList)
    (hwf_g : SparsePolyZp.WellFormed p g)
    (hred_g : SparsePolyZp.AllReduced p g.toList)
    (hp_size : 2 * p ≤ UInt64.size)
    :   Generated.__upoly_mod_ir f g = (SparsePolyZp.divmod f g).snd :=
  by
  unfold Generated.__upoly_mod_ir pair_vec_div5
  have h : HasPolyDivmod.polyDivmod (α := SparsePolyZp) = SparsePolyZp.divmod := rfl
  simpa [h]

end Refinement
