-- Auto-generated by cpp2lean v2 Pass 9 (refine_gen)
-- L1 → L2 refinement theorem skeletons

import CLPoly.Model
import CLPoly.Model
import CLPoly.Generated.Corpus
import CLPoly.Refinement.Basic
import CLPoly.Math.Univariate

set_option autoImplicit false

open Polynomial
open CLPoly.Math

namespace Refinement

variable {p : ℕ} [hp : Fact (Nat.Prime p)]

theorem Zp.toZMod_mul_weak (a b : Zp)
    (ha : a.prime.toNat = p) (hb : b.prime.toNat = p)
    (hp_size : 2 * p ≤ UInt64.size) :
    Zp.toZMod p (a * b) = Zp.toZMod p a * Zp.toZMod p b := by
  have hp_prime : Nat.Prime p := hp.out
  have hp_pos : 0 < p := Nat.Prime.pos hp_prime
  have hp_lt : p < UInt64.size := by nlinarith
  have ha_pos : 0 < a.prime.toNat := by
    rw [ha]; exact hp_pos
  have h_mod_lt : (a.val.toNat * b.val.toNat) % a.prime.toNat < UInt64.size := by
    have h_mod_lt_p_raw : (a.val.toNat * b.val.toNat) % a.prime.toNat < a.prime.toNat :=
      Nat.mod_lt (x := a.val.toNat * b.val.toNat) (y := a.prime.toNat) ha_pos
    have h_via_p : (a.val.toNat * b.val.toNat) % a.prime.toNat < p := by
      apply lt_of_lt_of_le h_mod_lt_p_raw ?_
      rw [ha]
    exact lt_trans h_via_p hp_lt
  unfold Zp.toZMod
  have h_val : (a * b).val.toNat = (a.val.toNat * b.val.toNat) % p := by
    calc
      (a * b).val.toNat = ((a.val.toNat * b.val.toNat) % a.prime.toNat).toUInt64.toNat := rfl
      _ = (a.val.toNat * b.val.toNat) % a.prime.toNat := by simp [h_mod_lt]
      _ = (a.val.toNat * b.val.toNat) % p := by rw [ha]
  rw [h_val]
  calc
    ((a.val.toNat * b.val.toNat) % p : ZMod p) = ((a.val.toNat * b.val.toNat : Nat) : ZMod p) := by
      rw [ZMod.natCast_mod]
    _ = (a.val.toNat : ZMod p) * (b.val.toNat : ZMod p) := by simp
    _ = Zp.toZMod p a * Zp.toZMod p b := rfl

theorem listSum_map_mul_prime_only (c : Zp) (l : List (UMonomial × Zp))
    (hred : ∀ x ∈ l, Zp.Reduced p x.snd) (hc_prime : c.prime.toNat = p)
    (hp_size : 2 * p ≤ UInt64.size) :
    listSum p (l.map (fun (m, x) => (m, x * c))) = C (c.toZMod p) * listSum p l := by
  induction l with
  | nil => simp
  | cons hd tl ih =>
    rcases hd with ⟨m, x⟩
    have hx_mem : (m, x) ∈ ((m, x) :: tl) := by simp
    have hx_red : Zp.Reduced p x := hred (m, x) hx_mem
    have hx_prime : x.prime.toNat = p := hx_red.1
    have hx_mul : Zp.toZMod p (x * c) = Zp.toZMod p x * Zp.toZMod p c :=
      Zp.toZMod_mul_weak x c hx_prime hc_prime hp_size
    have htl_red : ∀ x ∈ tl, Zp.Reduced p x.snd := by
      intro y hy; exact hred y (List.mem_cons_of_mem _ hy)
    simp [listSum, ih htl_red, hx_mul, Polynomial.C_mul_monomial, mul_add, mul_comm, add_comm, add_left_comm, add_assoc]

theorem __make_zp_ir_refines (p : ℕ) [hp : Fact (Nat.Prime p)]
    (val : Int64)
    (modulus : UInt64)
    :   Generated.__make_zp_ir val modulus = Zp.ofInt val.toInt modulus :=
  rfl

-- ============================================================
-- Helper lemmas for list operations
-- ============================================================

theorem drop_eq_get_cons {α : Type} (l : List α) (n : Nat) (h : n < l.length) :
    List.drop n l = l.get ⟨n, h⟩ :: List.drop (n + 1) l := by
  induction l generalizing n with
  | nil => simp at h
  | cons hd tl ih =>
    cases n with
    | zero => simp
    | succ n =>
      have hn : n < tl.length := by
        simpa [List.length_cons] using h
      calc
        List.drop (n + 1) (hd :: tl) = List.drop n tl := rfl
        _ = tl.get ⟨n, hn⟩ :: List.drop (n + 1) tl := ih n hn
        _ = (hd :: tl).get ⟨n + 1, h⟩ :: List.drop (n + 2) (hd :: tl) := by simp

theorem take_all_of_le {α : Type} (l : List α) (idx : Nat) (h : l.length ≤ idx) : List.take idx l = l := by
  revert h; induction l generalizing idx with
  | nil => intro; simp
  | cons hd tl ih =>
    intro h
    simp [List.length_cons] at h
    cases idx with
    | zero => simp at h
    | succ n =>
      have h' : tl.length ≤ n := Nat.le_of_succ_le_succ h
      simp [List.take, ih n h']

theorem drop_all_of_le {α : Type} (l : List α) (idx : Nat) (h : l.length ≤ idx) : List.drop idx l = [] := by
  revert h; induction l generalizing idx with
  | nil => intro; simp
  | cons hd tl ih =>
    intro h
    simp [List.length_cons] at h
    cases idx with
    | zero => simp at h
    | succ n =>
      have h' : tl.length ≤ n := Nat.le_of_succ_le_succ h
      simp [List.drop, ih n h']

theorem take_set_succ {α : Type} (l : List α) (idx : Nat) (v : α) (h : idx < l.length) :
    List.take (idx + 1) (l.set idx v) = List.take idx l ++ [v] := by
  induction l generalizing idx with
  | nil => simp at h
  | cons hd tl ih =>
    cases idx with
    | zero => simp
    | succ n =>
      have hn : n < tl.length := by
        simpa [List.length_cons] using h
      simp [ih n hn]

theorem drop_set_succ {α : Type} (l : List α) (idx : Nat) (v : α) (h : idx < l.length) :
    List.drop (idx + 1) (l.set idx v) = List.drop (idx + 1) l := by
  induction l generalizing idx with
  | nil => simp at h
  | cons hd tl ih =>
    cases idx with
    | zero => simp
    | succ n =>
      have hn : n < tl.length := by
        simpa [List.length_cons] using h
      simp [ih n hn]

-- ============================================================
-- Loop invariant for _loop___upoly_make_monic_0_ir
-- ============================================================

theorem loop_result_toList (f : SparsePolyZp) (c : Zp) (idx : Nat) (hidx : idx ≤ Array.size f) :
    (Generated._loop___upoly_make_monic_0_ir idx f c).snd.toList =
    (List.take idx (f.toList)) ++ (List.drop idx (f.toList)).map (fun (m, x) => (m, x * c)) := by
  have h_wf : WellFounded (λ (a b : SparsePolyZp × Nat) => Array.size a.1 - a.2 < Array.size b.1 - b.2) :=
    (measure (λ (p : SparsePolyZp × Nat) => Array.size p.1 - p.2)).wf
  refine h_wf.induction (f, idx) (C := λ p =>
    (Generated._loop___upoly_make_monic_0_ir p.2 p.1 c).snd.toList =
    (List.take p.2 (p.1.toList)) ++ (List.drop p.2 (p.1.toList)).map (fun (m, x) => (m, x * c))) ?_
  intro p ih
  rw [Generated._loop___upoly_make_monic_0_ir.eq_1]
  by_cases h : p.2 < Array.size p.1
  · simp [h]
    have hx_len : p.2 < p.1.toList.length := by simpa using h
    have h_measure : Array.size (Array.set! p.1 p.2 (p.1[p.2].1, p.1[p.2].2 * c)) - (p.2 + 1) < Array.size p.1 - p.2 := by
      simp; omega
    have h_ih : (Generated._loop___upoly_make_monic_0_ir (p.2 + 1) (Array.set! p.1 p.2 (p.1[p.2].1, p.1[p.2].2 * c)) c).snd.toList =
      (List.take (p.2 + 1) ((Array.set! p.1 p.2 (p.1[p.2].1, p.1[p.2].2 * c)).toList)) ++
      (List.drop (p.2 + 1) ((Array.set! p.1 p.2 (p.1[p.2].1, p.1[p.2].2 * c)).toList)).map (fun (m, x) => (m, x * c)) :=
      ih (Array.set! p.1 p.2 (p.1[p.2].1, p.1[p.2].2 * c), p.2 + 1) h_measure
    dsimp [Array.set!] at h_ih ⊢
    rw [h_ih]
    have h_toList : (Array.setIfInBounds p.1 p.2 (p.1[p.2].1, p.1[p.2].2 * c)).toList =
      (p.1.toList).set p.2 (p.1[p.2].1, p.1[p.2].2 * c) := by simp
    rw [h_toList]
    have htake : List.take (p.2 + 1) ((p.1.toList).set p.2 (p.1[p.2].1, p.1[p.2].2 * c)) =
        List.take p.2 (p.1.toList) ++ [(p.1[p.2].1, p.1[p.2].2 * c)] :=
      take_set_succ (p.1.toList) p.2 (p.1[p.2].1, p.1[p.2].2 * c) hx_len
    have hdrop : List.drop (p.2 + 1) ((p.1.toList).set p.2 (p.1[p.2].1, p.1[p.2].2 * c)) =
        List.drop (p.2 + 1) (p.1.toList) :=
      drop_set_succ (p.1.toList) p.2 (p.1[p.2].1, p.1[p.2].2 * c) hx_len
    rw [htake, hdrop]
    have h_drop_cons : List.drop p.2 (p.1.toList) = (p.1[p.2].1, p.1[p.2].2) :: List.drop (p.2 + 1) (p.1.toList) := by
      simpa using drop_eq_get_cons (p.1.toList) p.2 hx_len
    calc
      (List.take p.2 (p.1.toList) ++ [(p.1[p.2].1, p.1[p.2].2 * c)]) ++
          (List.drop (p.2 + 1) (p.1.toList)).map (fun (m, x) => (m, x * c))
          = List.take p.2 (p.1.toList) ++ ([(p.1[p.2].1, p.1[p.2].2 * c)] ++
            (List.drop (p.2 + 1) (p.1.toList)).map (fun (m, x) => (m, x * c))) := by simp [List.append_assoc]
      _ = List.take p.2 (p.1.toList) ++ (((p.1[p.2].1, p.1[p.2].2) :: List.drop (p.2 + 1) (p.1.toList)).map
            (fun (m, x) => (m, x * c))) := by simp
      _ = List.take p.2 (p.1.toList) ++ (List.drop p.2 (p.1.toList)).map (fun (m, x) => (m, x * c)) := by rw [h_drop_cons]
    have h_eq : (List.drop p.2 p.1.toList).map (fun (m, x) => (m, x * c)) =
      List.drop p.2 (List.map (fun x => (x.1, x.2 * c)) p.1.toList) := by
      rw [List.map_drop]
    rw [h_eq]
  · simp [h]
    have hidex : Array.size p.1 ≤ p.2 := by omega
    have hlen : p.1.toList.length ≤ p.2 := by simpa using hidex
    have htake : List.take p.2 (p.1.toList) = p.1.toList := take_all_of_le (p.1.toList) p.2 hlen
    have hdrop : List.drop p.2 (p.1.toList) = [] := drop_all_of_le (p.1.toList) p.2 hlen
    simp [htake, hdrop]
    exact hidex

theorem loop_toPoly (f : SparsePolyZp) (c : Zp)
    (hred_f : SparsePolyZp.AllReduced p f.toList) (hc_prime : c.prime.toNat = p)
    (hp_size : 2 * p ≤ UInt64.size) :
    SparsePolyZp.toPoly p (Generated._loop___upoly_make_monic_0_ir 0 f c).snd =
    C (c.toZMod p) * SparsePolyZp.toPoly p f := by
  have h_list : (Generated._loop___upoly_make_monic_0_ir 0 f c).snd.toList =
    (f.toList).map (fun (m, x) => (m, x * c)) := by
    have h_inv := loop_result_toList f c 0 (Nat.zero_le _)
    simpa [List.take, List.drop] using h_inv
  calc
    SparsePolyZp.toPoly p (Generated._loop___upoly_make_monic_0_ir 0 f c).snd
        = listSum p ((Generated._loop___upoly_make_monic_0_ir 0 f c).snd.toList) := rfl
    _ = listSum p ((f.toList).map (fun (m, x) => (m, x * c))) := by rw [h_list]
    _ = C (c.toZMod p) * listSum p (f.toList) :=
      listSum_map_mul_prime_only c f.toList hred_f hc_prime hp_size
    _ = C (c.toZMod p) * SparsePolyZp.toPoly p f := rfl

-- ============================================================
-- toPoly of scalarMul: filterMap removes zero terms,
-- but listSum is unchanged
-- ============================================================

theorem listSum_filterMap_eq_map (l : List (UMonomial × Zp)) (c : Zp)
    (hred : ∀ x ∈ l, Zp.Reduced p x.snd) :
    listSum p (l.filterMap (fun (p : UMonomial × Zp) =>
      let new_val := p.2 * c
      if new_val.val = 0 then none
      else some (p.1, new_val))) =
    listSum p (l.map (fun (p : UMonomial × Zp) => (p.1, p.2 * c))) := by
  induction l with
  | nil => simp
  | cons hd tl ih =>
    simp
    have hx_red : Zp.Reduced p hd.2 := hred hd (by simp)
    have hred_tl : ∀ x ∈ tl, Zp.Reduced p x.snd := by
      intro x hx; exact hred x (List.mem_cons_of_mem hd hx)
    by_cases hzero : (hd.2 * c).val = 0
    · simp [hzero, ih hred_tl, Zp.toZMod]
    · simp [hzero, ih hred_tl, Zp.toZMod]

theorem toPoly_scalarMul (c : Zp) (f : SparsePolyZp)
    (hred_f : SparsePolyZp.AllReduced p f.toList) (hc_prime : c.prime.toNat = p)
    (hp_size : 2 * p ≤ UInt64.size) :
    SparsePolyZp.toPoly p (SparsePolyZp.scalarMul c f) = C (c.toZMod p) * SparsePolyZp.toPoly p f := by
  unfold SparsePolyZp.scalarMul SparsePolyZp.toPoly
  have hfilter : (f.filterMap (fun (m, x) =>
    let new_val := x * c
    if new_val.val = 0 then none
    else some (m, new_val))).toList =
    (f.toList).filterMap (fun (p : UMonomial × Zp) =>
      let new_val := p.2 * c
      if new_val.val = 0 then none
      else some (p.1, new_val)) := by
    ext i; simp
  rw [hfilter]
  rw [listSum_filterMap_eq_map (f.toList) c hred_f,
    listSum_map_mul_prime_only c f.toList hred_f hc_prime hp_size]

-- ============================================================
-- Main theorem: __upoly_make_monic_ir_refines
-- ============================================================

lemma extGcdAux_a_1_0_1 (a : Int) : Zp.extGcdAux a 1 0 1 = (1, 1) := by
  simp [Zp.extGcdAux]

lemma modInv_one (p : UInt64) (hp : p.toNat ≠ 1) : Zp.modInv 1 p = 1 := by
  dsimp [Zp.modInv]
  have h1ne0 : (1 : UInt64) ≠ 0 := by decide
  simp [h1ne0, extGcdAux_a_1_0_1 (p.toNat : Int)]
  have h_mod_eq_one : (1 : Int) % (p.toNat : Int) = (1 : Int) := by
    have hp_cases : p.toNat = 0 ∨ 2 ≤ p.toNat := by
      by_cases h0 : p.toNat = 0
      · left; exact h0
      · right
        have h1pos : 1 ≤ p.toNat := Nat.one_le_of_lt (Nat.pos_of_ne_zero h0)
        by_contra! h_not2le
        have h_le1 : p.toNat ≤ 1 := by omega
        have h_eq1 : p.toNat = 1 := Nat.le_antisymm h_le1 h1pos
        exact hp h_eq1
    rcases hp_cases with (h0 | h2)
    · rw [h0]; simp
    · have h_1lt_nat : 1 < p.toNat := by
        calc
          1 < 2 := by decide
          _ ≤ p.toNat := h2
      have h1_nonneg : (0 : Int) ≤ 1 := by norm_num
      have h_1lt_int : (1 : Int) < (p.toNat : Int) := by exact_mod_cast h_1lt_nat
      exact Int.emod_eq_of_lt h1_nonneg h_1lt_int
  simp [h_mod_eq_one]

theorem __upoly_make_monic_ir_refines (p : ℕ) [hp : Fact (Nat.Prime p)]
    (f : SparsePolyZp)
    (hwf_f : SparsePolyZp.WellFormed p f)
    (hred_f : SparsePolyZp.AllReduced p f.toList)
    (hp_size : 2 * p ≤ UInt64.size)
    :   SparsePolyZp.toPoly p (Generated.__upoly_make_monic_ir f).snd = SparsePolyZp.toPoly p (SparsePolyZp.makeMonic f) :=
by
  have hfront_snd_eq : (SparsePolyZp.front! f).snd = f[0]!.snd := rfl
  by_cases hsize_zero : Array.size f = 0
  · -- f is empty: both sides equal toPoly(p, f)
    have hempty : f.isEmpty = true := by
      simp [Array.isEmpty, hsize_zero]
    have hf_empty : f = #[] := (Array.isEmpty_iff.mp hempty)
    subst hf_empty
    have hLHS : (Generated.__upoly_make_monic_ir #[]).snd = #[] := by
      unfold Generated.__upoly_make_monic_ir
      unfold Generated.__upoly_make_monic_ir_def
      have h_loop_snd : (Generated._loop___upoly_make_monic_0_ir 0 #[] (default : UMonomial × Zp).2.inv).snd = #[] := by
        unfold Generated._loop___upoly_make_monic_0_ir
        simp
      dsimp [SparsePolyZp.front!]
      by_cases h_cond_val : (default : UMonomial × Zp).2.val = Int64.toUInt64 1
      · simp [h_cond_val]
      · simp [h_cond_val, h_loop_snd]
    have hRHS : SparsePolyZp.makeMonic (#[] : SparsePolyZp) = #[] := by
      unfold SparsePolyZp.makeMonic
      simp
    simp [hLHS, hRHS]
  · -- f is not empty
    have hsize_pos : 0 < Array.size f := by
      by_contra! hzero
      apply hsize_zero
      omega
    have hempty_false : f.isEmpty = false := by
      apply Bool.eq_false_iff.mpr
      intro h
      have hsize : Array.size f = 0 := by
        simpa [Array.isEmpty] using h
      exact hsize_pos.ne' hsize
    have hfront_mem : f.front! ∈ f.toList := by
      have hpos' : 0 < f.toList.length := by
        have : f.toList.length = Array.size f := by simp
        rw [this]; exact hsize_pos
      have hval : f[0]! = (f.toList).get ⟨0, hpos'⟩ := by
        simp [hsize_pos, hpos']
      dsimp [SparsePolyZp.front!]
      rw [hval]
      exact (f.toList).get_mem ⟨0, hpos'⟩
    have hl_prime : (SparsePolyZp.front! f).snd.prime.toNat = p := by
      have hfront_red : Zp.Reduced p (SparsePolyZp.front! f).snd :=
        hred_f (SparsePolyZp.front! f) hfront_mem
      exact hfront_red.1
    have hl_inv_prime : (Zp.inv (SparsePolyZp.front! f).snd).prime.toNat = p := by
      simp [Zp.inv, hl_prime]
    have h_loop : SparsePolyZp.toPoly p (Generated._loop___upoly_make_monic_0_ir 0 f
        (Zp.inv ((SparsePolyZp.front! f).snd))).snd =
        C ((Zp.inv ((SparsePolyZp.front! f).snd)).toZMod p) * SparsePolyZp.toPoly p f :=
      loop_toPoly f (Zp.inv ((SparsePolyZp.front! f).snd)) hred_f hl_inv_prime hp_size
    have h_scalarMul : SparsePolyZp.toPoly p (SparsePolyZp.scalarMul
        (Zp.inv ((SparsePolyZp.front! f).snd)) f) =
        C ((Zp.inv ((SparsePolyZp.front! f).snd)).toZMod p) * SparsePolyZp.toPoly p f :=
      toPoly_scalarMul (Zp.inv ((SparsePolyZp.front! f).snd)) f hred_f hl_inv_prime hp_size
    by_cases hone_val : ((SparsePolyZp.front! f).snd).val = (1 : Int32)
    · -- leading coefficient is 1: generated code returns f directly
      have hgc : ((SparsePolyZp.front! f).snd).val = Int64.toUInt64 1 := by
        have h_cast_eq : (Int32.toInt64 1).toUInt64 = Int64.toUInt64 1 := by
          rfl
        simpa [h_cast_eq] using hone_val
      have hgen_snd : (Generated.__upoly_make_monic_ir f).snd = f := by
        unfold Generated.__upoly_make_monic_ir
        unfold Generated.__upoly_make_monic_ir_def
        simp [hgc, hsize_pos]
      have hmake_toPoly : SparsePolyZp.toPoly p (SparsePolyZp.makeMonic f) = SparsePolyZp.toPoly p f := by
        unfold SparsePolyZp.makeMonic
        simp [hempty_false]
        calc
          SparsePolyZp.toPoly p (SparsePolyZp.scalarMul (Zp.inv ((SparsePolyZp.front! f).snd)) f)
              = C ((Zp.inv ((SparsePolyZp.front! f).snd)).toZMod p) * SparsePolyZp.toPoly p f := h_scalarMul
          _ = C (1 : ZMod p) * SparsePolyZp.toPoly p f := by
            have h_one : (Zp.inv ((SparsePolyZp.front! f).snd)).toZMod p = (1 : ZMod p) := by
              unfold Zp.toZMod
              have h_val : (SparsePolyZp.front! f).snd.val = 1 := by
                simpa using hone_val
              have hprime_ne_one : ((SparsePolyZp.front! f).snd).prime.toNat ≠ 1 := by
                rw [hl_prime]
                exact Nat.Prime.ne_one (hp.out : Nat.Prime p)
              have h_modInv_eq_one : Zp.modInv 1 ((SparsePolyZp.front! f).snd).prime = 1 :=
                modInv_one ((SparsePolyZp.front! f).snd).prime hprime_ne_one
              simp [Zp.inv, h_val, h_modInv_eq_one]
            rw [h_one]
          _ = SparsePolyZp.toPoly p f := by simp
      calc
        SparsePolyZp.toPoly p (Generated.__upoly_make_monic_ir f).snd
            = SparsePolyZp.toPoly p f := by rw [hgen_snd]
        _ = SparsePolyZp.toPoly p (SparsePolyZp.makeMonic f) := by rw [hmake_toPoly]
    · have hne_val : ((SparsePolyZp.front! f).snd).val ≠ (1 : Int32) := hone_val
      have hne_beq : (((SparsePolyZp.front! f).snd).val == (1 : Int32)) = false := by
        apply Bool.eq_false_iff.mpr
        intro h
        apply hne_val
        simpa using h
      have hgen_snd : (Generated.__upoly_make_monic_ir f).snd =
          (Generated._loop___upoly_make_monic_0_ir 0 f
            (Zp.inv ((SparsePolyZp.front! f).snd))).snd := by
        unfold Generated.__upoly_make_monic_ir
        unfold Generated.__upoly_make_monic_ir_def
        dsimp
        have h_cast_eq : Int64.toUInt64 1 = (Int32.toInt64 1).toUInt64 := by
          rfl
        have h_ne_prop : f.front!.2.val ≠ Int64.toUInt64 1 := by
          rw [h_cast_eq]
          exact hne_val
        simp [h_ne_prop]
      have hmake : SparsePolyZp.makeMonic f =
          SparsePolyZp.scalarMul (Zp.inv ((SparsePolyZp.front! f).snd)) f := by
        unfold SparsePolyZp.makeMonic
        simp [hempty_false, hfront_snd_eq]
      calc
        SparsePolyZp.toPoly p (Generated.__upoly_make_monic_ir f).snd
            = SparsePolyZp.toPoly p ((Generated._loop___upoly_make_monic_0_ir 0 f
                (Zp.inv ((SparsePolyZp.front! f).snd))).snd) := by rw [hgen_snd]
        _ = C ((Zp.inv ((SparsePolyZp.front! f).snd)).toZMod p) * SparsePolyZp.toPoly p f := h_loop
        _ = SparsePolyZp.toPoly p (SparsePolyZp.scalarMul
              (Zp.inv ((SparsePolyZp.front! f).snd)) f) := by rw [← h_scalarMul]
        _ = SparsePolyZp.toPoly p (SparsePolyZp.makeMonic f) := by rw [hmake]

/--
  L1 `__upoly_divmod_ir` (C++: `clpoly/upolynomial.hh`) → L2 `SparsePolyZp.divmod`

  多项式长除法：q = f / g, r = f mod g

  C++ source: `clpoly/upolynomial.hh` — Clang AST → cpp2lean v2 Pass 1-8 → Corpus.lean
  L2 model : Algorithm/ZpArith.lean — hand-written, proven correct
  Bridge   : SparsePolyZp.toPoly (see Math/Univariate.lean)

  Proof status: closed below.
-/
theorem __upoly_divmod_ir_refines (p : ℕ) [hp : Fact (Nat.Prime p)]
    (q : SparsePolyZp)
    (r : SparsePolyZp)
    (f : SparsePolyZp)
    (g : SparsePolyZp)
    (hwf_q : SparsePolyZp.WellFormed p q)
    (hred_q : SparsePolyZp.AllReduced p q.toList)
    (hwf_r : SparsePolyZp.WellFormed p r)
    (hred_r : SparsePolyZp.AllReduced p r.toList)
    (hwf_f : SparsePolyZp.WellFormed p f)
    (hred_f : SparsePolyZp.AllReduced p f.toList)
    (hwf_g : SparsePolyZp.WellFormed p g)
    (hred_g : SparsePolyZp.AllReduced p g.toList)
    (hp_size : 2 * p ≤ UInt64.size)
    :   SparsePolyZp.toPoly p (Generated.__upoly_divmod_ir q r f g).1 = SparsePolyZp.toPoly p (SparsePolyZp.divmod f g).1 ∧
  SparsePolyZp.toPoly p (Generated.__upoly_divmod_ir q r f g).2 = SparsePolyZp.toPoly p (SparsePolyZp.divmod f g).2 :=
  by
  unfold Generated.__upoly_divmod_ir pair_vec_div5
  have h : HasPolyDivmod.polyDivmod (α := SparsePolyZp) = SparsePolyZp.divmod := rfl
  simp [h]

/--
  L1 `__upoly_mod_ir` (C++: `clpoly/upolynomial.hh`) → L2 `SparsePolyZp.divmod`

  多项式取模 remainder = f mod g

  C++ source: `clpoly/upolynomial.hh` — Clang AST → cpp2lean v2 Pass 1-8 → Corpus.lean
  L2 model : Algorithm/ZpArith.lean — hand-written, proven correct
  Bridge   : SparsePolyZp.toPoly (see Math/Univariate.lean)

  Proof status: closed below.
-/
theorem __upoly_mod_ir_refines (p : ℕ) [hp : Fact (Nat.Prime p)]
    (f : SparsePolyZp)
    (g : SparsePolyZp)
    (hwf_f : SparsePolyZp.WellFormed p f)
    (hred_f : SparsePolyZp.AllReduced p f.toList)
    (hwf_g : SparsePolyZp.WellFormed p g)
    (hred_g : SparsePolyZp.AllReduced p g.toList)
    (hp_size : 2 * p ≤ UInt64.size)
    :   Generated.__upoly_mod_ir f g = (SparsePolyZp.divmod f g).snd :=
  by
  unfold Generated.__upoly_mod_ir pair_vec_div5
  have h : HasPolyDivmod.polyDivmod (α := SparsePolyZp) = SparsePolyZp.divmod := rfl
  simpa [h]

end Refinement
