-- Auto-generated by cpp2lean v2 Pass 9 (refine_gen)
-- L1 → L2 refinement theorem skeletons

import CLPoly.Model
import CLPoly.Model
import CLPoly.Generated.Corpus
import CLPoly.Refinement.Basic
import CLPoly.Math.Univariate

set_option autoImplicit false

open Polynomial
open CLPoly.Math

namespace Refinement

variable {p : ℕ} [hp : Fact (Nat.Prime p)]

/--
  L1 `__symmetric_mod_ir` (C++: `clpoly/number/ZZ.hh`) → L2 `ZZ.symmetricMod`

  对称模运算：a mod m → [-m/2, m/2]

  C++ source: `clpoly/number/ZZ.hh` — Clang AST → cpp2lean v2 Pass 1-8 → Corpus.lean
  L2 model : Algorithm/ZZArith.lean — hand-written, proven correct
  Bridge   : SparsePolyZp.toPoly (see Math/Univariate.lean)

  Proof status: Skeleton (sorry) — fill to complete L1→L2 verification chain
-/
theorem __symmetric_mod_ir_refines (p : ℕ) [hp : Fact (Nat.Prime p)]
    (a : ZZ)
    (m : ZZ)
    :   Generated.__symmetric_mod_ir a m = ZZ.symmetricMod a m :=
by
  unfold Generated.__symmetric_mod_ir ZZ.symmetricMod
  dsimp
  -- Goal:
  --   (if ZZ.fdiv_r 0 a m > ZZ.fdiv_q 0 m 2 then ZZ.fdiv_r 0 a m - m else ZZ.fdiv_r 0 a m) =
  --   (if a.fmod m * 2 ≤ m then a.fmod m else a.fmod m - m)
  have h_fdiv_r : ZZ.fdiv_r 0 a m = a.fmod m := rfl
  have h_fdiv_q : ZZ.fdiv_q 0 m ((2 : Int32).toInt) = Int.fdiv m 2 := rfl
  -- But dsimp simplified (2 : Int32).toInt to 2 in the goal, so the LHS pattern is ZZ.fdiv_q 0 m 2
  -- We need a lemma that ZZ.fdiv_q 0 m 2 = Int.fdiv m 2
  have h_fdiv_q' : ZZ.fdiv_q 0 m 2 = Int.fdiv m 2 := by
    unfold ZZ.fdiv_q; simp
  rw [h_fdiv_r, h_fdiv_q']
  rw [Int.fdiv_eq_ediv_of_nonneg m (by norm_num : 0 ≤ (2 : Int))]
  set r := a.fmod m with hr
  by_cases h : r * 2 ≤ m
  · have h_not_gt : ¬ (r > m / 2) := by omega
    simp [h, h_not_gt]
  · have h_gt : r > m / 2 := by omega
    simp [h, h_gt]

/--
  L1 `__binomial_ir` (C++: `clpoly/polynomial_factorize_univar.hh`) → L2 `ZZ.binomial`

  二项式系数 n choose k

  C++ source: `clpoly/polynomial_factorize_univar.hh` — Clang AST → cpp2lean v2 Pass 1-8 → Corpus.lean
  L2 model : Algorithm/ZZArith.lean — hand-written, proven correct
  Bridge   : SparsePolyZp.toPoly (see Math/Univariate.lean)

  Proof status: Skeleton (sorry) — fill to complete L1→L2 verification chain
-/
theorem my_mul_add (a b c : Nat) : a * (b + c) = a * b + a * c := by
  rw [Nat.mul_comm a (b + c), Nat.add_mul b c a, Nat.mul_comm b a, Nat.mul_comm c a]

theorem myChoose_one (n : Nat) : Nat.myChoose n 1 = n := by
  induction n with
  | zero => simp [Nat.myChoose]
  | succ n ih =>
    unfold Nat.myChoose
    rw [ih]
    simp [Nat.myChoose]

theorem myChoose_eq_zero_of_lt {n j : Nat} (h : n < j) : Nat.myChoose n j = 0 := by
  induction n generalizing j with
  | zero =>
    cases j
    · exact (Nat.not_lt_zero _ h).elim
    · simp [Nat.myChoose]
  | succ n ih =>
    cases j
    · exact (Nat.not_lt_zero _ h).elim
    · case succ j =>
      have hn_j : n < j := by omega
      have hn_jsucc : n < j+1 := by omega
      unfold Nat.myChoose
      have h1 : Nat.myChoose n (j+1) = 0 := ih (j := j+1) hn_jsucc
      have h2 : Nat.myChoose n j = 0 := ih (j := j) hn_j
      rw [h1, h2]

/-- 组合恒等式：C(n, k+1) * (k+1) = C(n, k) * (n - k) -/
theorem myChoose_mul_eq (n k : Nat) : Nat.myChoose n (k + 1) * (k + 1) = Nat.myChoose n k * (n - k) := by
  revert n
  induction k with
  | zero =>
    intro n
    simp [myChoose_one, Nat.myChoose]
  | succ k ih =>
    intro n
    induction n with
    | zero => simp [Nat.myChoose]
    | succ n ih_n =>
      simp [Nat.myChoose]
      rw [Nat.add_mul, Nat.add_mul]
      have h_ih_n : Nat.myChoose n (k + 2) * (k + 2) = Nat.myChoose n (k + 1) * (n - (k + 1)) := ih_n
      rw [h_ih_n]
      have h_eq_ih : Nat.myChoose n (k + 1) * (k + 1) = Nat.myChoose n k * (n - k) := ih n
      by_cases hk_le_n : k + 1 ≤ n
      · have h_n_sub : n - k = (n + 1) - (k + 1) := by omega
        have h_sum : (n - (k + 1)) + (k + 2) = (n - k) + (k + 1) := by omega
        calc
          Nat.myChoose n (k + 1) * (n - (k + 1)) + Nat.myChoose n (k + 1) * (k + 2)
              = Nat.myChoose n (k + 1) * ((n - (k + 1)) + (k + 2)) := by rw [← my_mul_add]
          _ = Nat.myChoose n (k + 1) * ((n - k) + (k + 1)) := by rw [h_sum]
          _ = Nat.myChoose n (k + 1) * (n - k) + Nat.myChoose n (k + 1) * (k + 1) := by rw [my_mul_add]
           _ = Nat.myChoose n (k + 1) * (n - k) + Nat.myChoose n k * (n - k) := by rw [h_eq_ih]
      · have hk_gt_n : n < k + 1 := by omega
        have h_zero : Nat.myChoose n (k + 1) = 0 := myChoose_eq_zero_of_lt hk_gt_n
        have h_eq' : Nat.myChoose n k * (n - k) = 0 := by
          rw [← h_eq_ih, h_zero, zero_mul]
        calc
          Nat.myChoose n (k + 1) * (n - (k + 1)) + Nat.myChoose n (k + 1) * (k + 2)
              = 0 := by simp [h_zero]
          _ = Nat.myChoose n k * (n - k) := by rw [h_eq'.symm]
        simp [h_zero]

theorem __binomial_ir_refines (p : ℕ) [hp : Fact (Nat.Prime p)]
    (n : Int64)
    (k : Int64)
    :   Generated.__binomial_ir n k = ZZ.binomial n k :=
by
  -- Using native_decide for each concrete pair is infeasible.
  -- Instead, prove equality by reduction to Nat.myChoose
  -- using the fact that both sides compute the binomial coefficient.
  -- For now, this is a known gap that requires a full proof of
  -- the loop correctness by induction on the Nat counter.
  
  -- The key lemma needed: myChoose_mul_eq (being proved above)
  -- and a lemma connecting the loop to Nat.myChoose via Induction
  
  sorry

/--
  L1 `__isqrt_ceil_ir` (C++: `clpoly/number/ZZ.hh`) → L2 `ZZ.isqrtCeil`

  向上取整平方根 ceil(sqrt(n))

  C++ source: `clpoly/number/ZZ.hh` — Clang AST → cpp2lean v2 Pass 1-8 → Corpus.lean
  L2 model : Algorithm/ZZArith.lean — hand-written, proven correct
  Bridge   : SparsePolyZp.toPoly (see Math/Univariate.lean)

  Proof status: Skeleton (sorry) — fill to complete L1→L2 verification chain
-/
theorem __isqrt_ceil_ir_refines (p : ℕ) [hp : Fact (Nat.Prime p)]
    (n : ZZ)
    :   Generated.__isqrt_ceil_ir n = ZZ.isqrtCeil n :=
  by
  sorry

end Refinement
