-- Auto-generated by cpp2lean v2 Pass 9 (refine_gen)
-- L1 → L2 refinement theorem skeletons

import CLPoly.Model
import CLPoly.Model
import CLPoly.Generated.Corpus
import CLPoly.Refinement.Basic
import CLPoly.Math.Univariate

set_option autoImplicit false

open Polynomial
open CLPoly.Math

namespace Refinement

variable {p : ℕ} [hp : Fact (Nat.Prime p)]

/--
  L1 `__symmetric_mod_ir` (C++: `clpoly/number/ZZ.hh`) → L2 `ZZ.symmetricMod`

  对称模运算：a mod m → [-m/2, m/2]

  C++ source: `clpoly/number/ZZ.hh` — Clang AST → cpp2lean v2 Pass 1-8 → Corpus.lean
  L2 model : Algorithm/ZZArith.lean — hand-written, proven correct
  Bridge   : SparsePolyZp.toPoly (see Math/Univariate.lean)

  Proof status: Skeleton (sorry) — fill to complete L1→L2 verification chain
-/
theorem __symmetric_mod_ir_refines (p : ℕ) [hp : Fact (Nat.Prime p)]
    (a : ZZ)
    (m : ZZ)
    :   Generated.__symmetric_mod_ir a m = ZZ.symmetricMod a m :=
by
  unfold Generated.__symmetric_mod_ir ZZ.symmetricMod
  dsimp
  -- Goal:
  --   (if ZZ.fdiv_r 0 a m > ZZ.fdiv_q 0 m 2 then ZZ.fdiv_r 0 a m - m else ZZ.fdiv_r 0 a m) =
  --   (if a.fmod m * 2 ≤ m then a.fmod m else a.fmod m - m)
  have h_fdiv_r : ZZ.fdiv_r 0 a m = a.fmod m := rfl
  have h_fdiv_q : ZZ.fdiv_q 0 m ((2 : Int32).toInt) = Int.fdiv m 2 := rfl
  -- But dsimp simplified (2 : Int32).toInt to 2 in the goal, so the LHS pattern is ZZ.fdiv_q 0 m 2
  -- We need a lemma that ZZ.fdiv_q 0 m 2 = Int.fdiv m 2
  have h_fdiv_q' : ZZ.fdiv_q 0 m 2 = Int.fdiv m 2 := by
    unfold ZZ.fdiv_q; simp
  rw [h_fdiv_r, h_fdiv_q']
  rw [Int.fdiv_eq_ediv_of_nonneg m (by norm_num : 0 ≤ (2 : Int))]
  set r := a.fmod m with hr
  by_cases h : r * 2 ≤ m
  · have h_not_gt : ¬ (r > m / 2) := by omega
    simp [h, h_not_gt]
  · have h_gt : r > m / 2 := by omega
    simp [h, h_gt]

/--
  L1 `__binomial_ir` (C++: `clpoly/polynomial_factorize_univar.hh`) → L2 `ZZ.binomial`

  二项式系数 n choose k

  C++ source: `clpoly/polynomial_factorize_univar.hh` — Clang AST → cpp2lean v2 Pass 1-8 → Corpus.lean
  L2 model : Algorithm/ZZArith.lean — hand-written, proven correct
  Bridge   : SparsePolyZp.toPoly (see Math/Univariate.lean)

  Proof status: Skeleton (sorry) — fill to complete L1→L2 verification chain
-/
theorem __binomial_ir_refines (p : ℕ) [hp : Fact (Nat.Prime p)]
    (n : Int64)
    (k : Int64)
    :   Generated.__binomial_ir n k = ZZ.binomial n k :=
  by
  sorry

/--
  L1 `__isqrt_ceil_ir` (C++: `clpoly/number/ZZ.hh`) → L2 `ZZ.isqrtCeil`

  向上取整平方根 ceil(sqrt(n))

  C++ source: `clpoly/number/ZZ.hh` — Clang AST → cpp2lean v2 Pass 1-8 → Corpus.lean
  L2 model : Algorithm/ZZArith.lean — hand-written, proven correct
  Bridge   : SparsePolyZp.toPoly (see Math/Univariate.lean)

  Proof status: Skeleton (sorry) — fill to complete L1→L2 verification chain
-/
theorem __isqrt_ceil_ir_refines (p : ℕ) [hp : Fact (Nat.Prime p)]
    (n : ZZ)
    :   Generated.__isqrt_ceil_ir n = ZZ.isqrtCeil n :=
  by
  sorry

end Refinement
